export interface FeedAdditive {
  id: string;
  category: 1 | 2 | 3 | 4;
  categoryLabel: string;
  functionalGroup: string;
  eNumber: string;
  name: string;
  provisions: string;
}

const ANIMAL_FEED_ADDITIVES: FeedAdditive[] = [
  // ═══════════════════════════════════════════════
  // CATEGORY 1 – Technological Additives
  // ═══════════════════════════════════════════════

  // 1a – Preservatives
  { id: "1-001", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 200", name: "Sorbic acid", provisions: "" },
  { id: "1-002", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 202", name: "Potassium sorbate", provisions: "" },
  { id: "1-003", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 236", name: "Formic acid", provisions: "" },
  { id: "1-004", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 237", name: "Sodium formate", provisions: "" },
  { id: "1-005", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "1a237a", name: "Potassium diformate", provisions: "" },
  { id: "1-006", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 238", name: "Calcium formate", provisions: "" },
  { id: "1-007", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 250", name: "Sodium nitrite", provisions: "[الكلاب؛ القطط]" },
  { id: "1-008", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 260", name: "Acetic acid", provisions: "" },
  { id: "1-009", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 262", name: "Sodium diacetate", provisions: "" },
  { id: "1-010", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 263", name: "Calcium acetate", provisions: "" },
  { id: "1-011", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 270", name: "Lactic acid", provisions: "" },
  { id: "1-012", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 280", name: "Propionic acid", provisions: "" },
  { id: "1-013", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 281", name: "Sodium propionate", provisions: "" },
  { id: "1-014", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 282", name: "Calcium propionate", provisions: "" },
  { id: "1-015", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 284", name: "Ammonium propionate", provisions: "" },
  { id: "1-016", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 295", name: "Ammonium formate", provisions: "" },
  { id: "1-017", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 296", name: "DL-Malic acid", provisions: "" },
  { id: "1-018", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "1a297", name: "Fumaric acid", provisions: "[الدواجن؛ صغار الحيوانات المغذّاة ببدائل الحليب؛ سائر الأنواع]" },
  { id: "1-019", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 327", name: "Calcium lactate", provisions: "" },
  { id: "1-020", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "E 330", name: "Citric acid", provisions: "" },
  { id: "1-021", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "1a338", name: "Orthophosphoric acid", provisions: "" },
  { id: "1-022", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد حافظة", eNumber: "1a700", name: "Sodium benzoate 140 g/kg, Propionic acid 370 g/kg, Sodium propionate 110 g/kg", provisions: "[الدواجن؛ الأبقار؛ الخراف؛ الماعز؛ الأرانب؛ الخيول]" },

  // 1b – Antioxidants
  { id: "1-023", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "3a300", name: "Ascorbic acid", provisions: "" },
  { id: "1-024", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "1b301", name: "Sodium ascorbate", provisions: "" },
  { id: "1-025", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "1b302", name: "Calcium ascorbate", provisions: "" },
  { id: "1-026", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "1b304", name: "Ascorbyl palmitate", provisions: "" },
  { id: "1-027", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "1b306(i)", name: "Tocopherol extracts from vegetable oils", provisions: "" },
  { id: "1-028", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "1b306(ii)", name: "Tocopherol-rich extracts from vegetable oils (delta rich)", provisions: "" },
  { id: "1-029", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "1b307", name: "Alpha-tocopherol", provisions: "" },
  { id: "1-030", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "E 310", name: "Propyl gallate", provisions: "" },
  { id: "1-031", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "E 320", name: "Butylated hydroxyanisole (BHA)", provisions: "جميع الأنواع" },
  { id: "1-032", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "E 321", name: "Butylated hydroxytoluene (BHT)", provisions: "جميع الأنواع" },
  { id: "1-033", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضادات أكسدة", eNumber: "E 324", name: "Ethoxyquin", provisions: "جميع الأنواع" },

  // 1c/d/e/f – Emulsifying / stabilizing / thickeners / gelling
  { id: "1-034", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 322", name: "Lecithins", provisions: "(كمستحلب فقط)" },
  { id: "1-035", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 401", name: "Sodium alginate", provisions: "[الأسماك؛ الحيوانات الأليفة وغير المنتجة للغذاء]" },
  { id: "1-036", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 406", name: "Agar", provisions: "[الحيوانات الأليفة وغير المنتجة للغذاء]" },
  { id: "1-037", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 407", name: "Carrageenan", provisions: "[الحيوانات الأليفة وغير المنتجة للغذاء]" },
  { id: "1-038", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 410", name: "Locust bean gum (Carob gum)", provisions: "" },
  { id: "1-039", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 412", name: "Guar gum", provisions: "" },
  { id: "1-040", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 413", name: "Tragacanth", provisions: "" },
  { id: "1-041", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 414", name: "Acacia (Gum arabic)", provisions: "" },
  { id: "1-042", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 415", name: "Xanthan gum", provisions: "" },
  { id: "1-043", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 433", name: "Polyoxyethylene (20)-sorbitan monooleate", provisions: "" },
  { id: "1-044", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 460", name: "Microcrystalline cellulose", provisions: "" },
  { id: "1-045", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 461", name: "Methylcellulose", provisions: "" },
  { id: "1-046", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 462", name: "Ethylcellulose", provisions: "" },
  { id: "1-047", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 463", name: "Hydroxypropylcellulose", provisions: "" },
  { id: "1-048", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 464", name: "Hydroxypropylmethylcellulose", provisions: "" },
  { id: "1-049", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 466", name: "Carboxymethylcellulose (Sodium salt of carboxymethyl ether of cellulose)", provisions: "" },
  { id: "1-050", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 484", name: "Glyceryl polyethyleneglycol ricinoleate", provisions: "" },
  { id: "1-051", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 487", name: "Polyethyleneglycol ester of fatty acids from soya oil", provisions: "[العجول]" },
  { id: "1-052", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 493", name: "Sorbitan monolaurate", provisions: "" },
  { id: "1-053", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مستحلب ومثبتات ومواد تساعد على اللزوجة وعوامل تزيد الهلامية", eNumber: "E 499", name: "Cassia gum", provisions: "[الكلاب؛ القطط]" },

  // 1g – Binders / anticaking
  { id: "1-054", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 535", name: "Sodium Ferrocyanide", provisions: "" },
  { id: "1-055", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 536", name: "Potassium Ferrocyanide", provisions: "" },
  { id: "1-056", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 551a", name: "Silicic acid, precipitated and dried", provisions: "" },
  { id: "1-057", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 551b", name: "Colloidal silica", provisions: "" },
  { id: "1-058", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 551c", name: "Kieselgur (diatomaceous earth, purified)", provisions: "" },
  { id: "1-059", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 552", name: "Calcium silicate, synthetic", provisions: "" },
  { id: "1-060", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 554", name: "Sodium aluminosilicate, synthetic", provisions: "" },
  { id: "1-061", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 558", name: "Bentonite-montmorillonite", provisions: "" },
  { id: "1-062", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 559", name: "Kaolinitic clays, free of asbestos", provisions: "" },
  { id: "1-063", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 560", name: "Natural mixtures of steatites and chlorite", provisions: "" },
  { id: "1-064", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 561", name: "Vermiculite", provisions: "" },
  { id: "1-065", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 562", name: "Sepiolite", provisions: "" },
  { id: "1-066", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 563", name: "Sepiolitic clay", provisions: "" },
  { id: "1-067", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 565", name: "Lignosulphonates", provisions: "" },
  { id: "1-068", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 566", name: "Natrolite-phonolite", provisions: "" },
  { id: "1-069", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 567", name: "Clinoptilolite of volcanic origin", provisions: "[الدواجن]" },
  { id: "1-070", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "E 599", name: "Perlite", provisions: "" },
  { id: "1-071", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "1g557", name: "Montmorillonite-Illite", provisions: "[جميع الأنواع]" },
  { id: "1-072", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "1g568", name: "Clinoptilolite of sedimentary origin", provisions: "[جميع الأنواع]" },
  { id: "1-073", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "1g598", name: "Dolomite-Magnesite", provisions: "[أبقار الحلاب وسائر المجترات المنتجة للحليب]" },
  { id: "1-074", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تساعد على التلاصق وعوامل تمنع من التكتل", eNumber: "1m558i", name: "Bentonite", provisions: "[جميع الأنواع]" },

  // 1h – Radioactive caesium binders
  { id: "1-075", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مواد تقلل من امتصاص أو تزيد من إخراج المواد المشعة", eNumber: "1.1", name: "Ferric (III) ammonium hexacyanoferrate (II)", provisions: "[المجترات؛ العجول والحملان والجداء قبل الاجترار]" },

  // 1i – Anticaking agents
  { id: "1-076", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تمنع من التكتل", eNumber: "1g568", name: "Clinoptilolite of sedimentary origin", provisions: "[جميع الأنواع]" },
  { id: "1-077", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "عوامل تمنع من التكتل", eNumber: "1i534", name: "Iron sodium tartrates", provisions: "[جميع الأنواع]" },

  // 1j – Acidity regulators
  { id: "1-078", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "منظمات الحمضية", eNumber: "296", name: "DL- and L-Malic acid", provisions: "[القطط؛ الكلاب]" },
  { id: "1-079", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "منظمات الحمضية", eNumber: "1j524", name: "Sodium hydroxide", provisions: "[القطط؛ الكلاب؛ أسماك الزينة]" },
  { id: "1-080", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "منظمات الحمضية", eNumber: "1j514ii", name: "Sodium bisulphate", provisions: "[جميع الأنواع ما عدا القطط والمنك والحيوانات الأليفة غير المنتجة للغذاء]" },

  // k1 – Enzymes
  { id: "1-081", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Alpha-amylase EC 3.2.1.1 from Aspergillus oryzae CBS 585.94", provisions: "" },
  { id: "1-082", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Alpha-amylase EC 3.2.1.1 from Aspergillus oryzae DS114", provisions: "" },
  { id: "1-083", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Alpha-amylase EC 3.2.1.1 from Bacillus amyloliquefaciens DSM 9553", provisions: "" },
  { id: "1-084", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Alpha-amylase EC 3.2.1.1 from Bacillus amyloliquefaciens SD80", provisions: "" },
  { id: "1-085", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Alpha-amylase EC 3.2.1.1 from Bacillus subtilis DS098", provisions: "" },
  { id: "1-086", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Cellulase EC 3.2.1.4 from Aspergillus niger CBS 120604", provisions: "" },
  { id: "1-087", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Cellulase EC 3.2.1.4 from Trichoderma longibrachiatum ATCC PTA-10001", provisions: "" },
  { id: "1-088", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Cellulase EC 3.2.1.4 from Trichoderma longibrachiatum ATCC 74252", provisions: "" },
  { id: "1-089", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Beta-glucanase EC 3.2.1.6 from Aspergillus niger MUCL 39199", provisions: "" },
  { id: "1-090", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Xylanase EC 3.2.1.8 from Trichoderma longibrachiatum MUCL 39203", provisions: "" },
  { id: "1-091", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "إنزيمات", eNumber: "—", name: "Xylanase EC 3.2.1.8 from Trichoderma longibrachiatum CBS 614.94", provisions: "" },

  // k2 – Microorganisms
  { id: "1-092", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Bacillus subtilis MBS-BS-01", provisions: "" },
  { id: "1-093", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Enterococcus faecium CCM 6226", provisions: "" },
  { id: "1-094", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Enterococcus faecium CNCM I-3236 / ATCC 19434", provisions: "" },
  { id: "1-095", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus buchneri CCM 1819", provisions: "" },
  { id: "1-096", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Enterococcus faecium SF202 DSM 4788 ATCC 53519", provisions: "" },
  { id: "1-097", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Enterococcus faecium SF301 DSM 4789 ATCC 55593", provisions: "" },
  { id: "1-098", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus buchneri KKP. 907", provisions: "" },
  { id: "1-099", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus casei ATCC 7469", provisions: "" },
  { id: "1-100", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus plantarum C KKP/788/p", provisions: "" },
  { id: "1-101", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus plantarum DSM 11520", provisions: "" },
  { id: "1-102", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus plantarum K KKP/593/p", provisions: "" },
  { id: "1-103", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus plantarum LP287 DSM 5257 ATCC 55058", provisions: "" },
  { id: "1-104", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus plantarum LP329 DSM 5258 ATCC 55942", provisions: "" },
  { id: "1-105", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactobacillus plantarum MBS-LP-01", provisions: "" },
  { id: "1-106", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Lactococcus lactis CCM 4754, NCIMB 30117", provisions: "" },
  { id: "1-107", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Pediococcus pentosaceus MBS-PP-01", provisions: "" },
  { id: "1-108", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "ميكروبات جرثومية", eNumber: "—", name: "Saccharomyces cerevisiae IFO 0203", provisions: "" },

  // k3 – Substances (silage)
  { id: "1-109", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "—", name: "Hexamethylene tetramine", provisions: "[الأبقار؛ الأغنام؛ الدواجن؛ الأرانب؛ الخيول؛ الماعز]" },
  { id: "1-110", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "—", name: "Sodium benzoate", provisions: "" },
  { id: "1-111", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "E 250", name: "Sodium nitrite", provisions: "" },
  { id: "1-112a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k1009", name: "Pediococcus pentosaceus", provisions: "" },
  { id: "1-112b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k1010", name: "Pediococcus pentosaceus", provisions: "" },
  { id: "1-112c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k1011", name: "Pediococcus pentosaceus", provisions: "" },
  { id: "1-113", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "k202", name: "Potassium sorbate", provisions: "" },
  { id: "1-114a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20601", name: "Enterococcus faecium NCIMB 10415", provisions: "[جميع الأنواع]" },
  { id: "1-114b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20602", name: "Enterococcus faecium NCIMB 10415", provisions: "[جميع الأنواع]" },
  { id: "1-115a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2071", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2073", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2078", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115d", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2079", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115e", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20713", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115f", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20714", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115g", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20716", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115h", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20717", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115i", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20718", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115j", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20719", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115k", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20720", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115l", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20721", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115m", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20722", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115n", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20723", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115o", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20724", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115p", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20725", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115q", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20726", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115r", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20727", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115s", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20728", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115t", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20729", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115u", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20730", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115v", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20731", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115w", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20732", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115x", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20736", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115y", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20737", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115z", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20743", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115aa", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20746", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115ab", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20749", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115ac", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20750", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115ad", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20751", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-115ae", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20812", name: "Lactobacillus plantarum (DSM 21762)", provisions: "" },
  { id: "1-116a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20710", name: "Lactobacillus brevis", provisions: "" },
  { id: "1-116b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20715", name: "Lactobacillus brevis", provisions: "" },
  { id: "1-116c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20744", name: "Lactobacillus brevis", provisions: "" },
  { id: "1-116d", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20745", name: "Lactobacillus brevis", provisions: "" },
  { id: "1-117", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20711", name: "Lactobacillus rhamnosus (NCIMB 30121)", provisions: "" },
  { id: "1-118a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2072", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2074", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2075", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118d", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20733", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118e", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20734", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118f", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20738", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118g", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20739", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118h", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20740", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-118i", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20741", name: "Lactobacillus buchneri", provisions: "" },
  { id: "1-119", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20735", name: "Lactobacillus casei ATTC PTA 6135", provisions: "" },
  { id: "1-120", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20742", name: "Lactobacillus kefiri DSM 19455", provisions: "" },
  { id: "1-121", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20747", name: "Lactobacillus fermentum NCIMB 30169", provisions: "" },
  { id: "1-122a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k20748", name: "Lactobacillus paracasei", provisions: "" },
  { id: "1-122b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2076", name: "Lactobacillus paracasei", provisions: "" },
  { id: "1-122c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2077", name: "Lactobacillus paracasei", provisions: "" },
  { id: "1-123a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2081", name: "Lactococcus lactis", provisions: "" },
  { id: "1-123b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2082", name: "Lactococcus lactis", provisions: "" },
  { id: "1-123c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2083", name: "Lactococcus lactis", provisions: "" },
  { id: "1-124", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k21008", name: "Preparation of Lactobacillus plantarum NCIMB 30238 and Pediococcus pentosaceus NCIMB 30237", provisions: "" },
  { id: "1-125a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k21009", name: "Pediococcus acidilactici CNCM I-3237", provisions: "[جميع الأنواع]" },
  { id: "1-125b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k21013", name: "Pediococcus acidilactici CNCM I-3237", provisions: "[جميع الأنواع]" },
  { id: "1-125c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2102", name: "Pediococcus acidilactici CNCM I-3237", provisions: "[جميع الأنواع]" },
  { id: "1-125d", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2104", name: "Pediococcus acidilactici CNCM I-3237", provisions: "[جميع الأنواع]" },
  { id: "1-126a", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2101", name: "Pediococcus pentosaceus DSM 16244", provisions: "" },
  { id: "1-126b", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2103", name: "Pediococcus pentosaceus DSM 16244", provisions: "" },
  { id: "1-126c", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2105", name: "Pediococcus pentosaceus DSM 16244", provisions: "" },
  { id: "1-126d", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2106", name: "Pediococcus pentosaceus DSM 16244", provisions: "" },
  { id: "1-126e", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2107", name: "Pediococcus pentosaceus DSM 16244", provisions: "" },
  { id: "1-127", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k2111", name: "Propionibacterium acidipropionici CNCM MA 26/4U", provisions: "" },
  { id: "1-128", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k236", name: "Formic acid", provisions: "" },
  { id: "1-129", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k237", name: "Sodium formate", provisions: "" },
  { id: "1-130", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k280", name: "Propionic acid", provisions: "[جميع الأنواع]" },
  { id: "1-131", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k281", name: "Sodium propionate", provisions: "[جميع الأنواع]" },
  { id: "1-132", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k284", name: "Ammonium propionate", provisions: "" },
  { id: "1-133", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "مضافات سيلاج", eNumber: "1k301", name: "Sodium benzoate", provisions: "" },

  // 1m – Mycotoxin binders
  { id: "1-134", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "محيدات السموم الفطرية", eNumber: "1m01", name: "Micro-organism strain DSM 11798 of the Coriobacteriaceae family (DON reduction)", provisions: "" },
  { id: "1-135", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "محيدات السموم الفطرية", eNumber: "1m03", name: "Fumonisin esterase EC 3.1.1.87 produced by Komagataella pastoris DSM 26643", provisions: "" },
  { id: "1-136", category: 1, categoryLabel: "الإضافات التقنية", functionalGroup: "محيدات السموم الفطرية", eNumber: "1m558", name: "Bentonite", provisions: "[المجترات؛ الدواجن]" },

  // ═══════════════════════════════════════════════
  // CATEGORY 2 – Sensory Additives
  // ═══════════════════════════════════════════════

  // 2a – Carotenoids and xanthophylls
  { id: "2-001", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل", eNumber: "E 160c", name: "Capsanthin", provisions: "[الدواجن ما عدا الرومي]" },
  { id: "2-002", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل", eNumber: "E 160f", name: "Ethyl ester of beta-apo-8'-carotenoic acid", provisions: "[الدواجن]" },
  { id: "2-003", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل", eNumber: "E 161b", name: "Lutein", provisions: "[الدواجن]" },
  { id: "2-004", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل", eNumber: "E 161h", name: "Zeaxanthin", provisions: "[الدواجن]" },
  { id: "2-005", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل", eNumber: "E 161i", name: "Citranaxanthin", provisions: "[البياض]" },
  { id: "2-006", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل", eNumber: "E 161y", name: "Astaxanthin-rich Phaffia rhodozyma (ATCC SD-5340)", provisions: "[السلمون؛ التروتة]" },
  { id: "2-007", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – إضافة لون لمنتجات الحيوان", eNumber: "2a161j", name: "Astaxanthin", provisions: "[الأسماك؛ القشريات]" },
  { id: "2-008", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "2a161j", name: "Astaxanthin", provisions: "[أسماك الزينة]" },

  // 2a – Other colourants
  { id: "2-009", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 102", name: "Tartrazine", provisions: "[الكلاب؛ القطط]" },
  { id: "2-010", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 110", name: "Sunset yellow FCF", provisions: "[الكلاب؛ القطط]" },
  { id: "2-011", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 120", name: "Carmine (Carmine Lake WSP 50%)", provisions: "[الكلاب؛ القطط]" },
  { id: "2-012", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 124", name: "Ponceau 4 R", provisions: "[الكلاب؛ القطط]" },
  { id: "2-013", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 127", name: "Erythrosine", provisions: "[الكلاب؛ القطط]" },
  { id: "2-014", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 129", name: "Allura Red", provisions: "[الكلاب؛ القطط]" },
  { id: "2-015", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 132", name: "Indigotine", provisions: "[الكلاب؛ القطط]" },
  { id: "2-016", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 133", name: "Brilliant Blue FCF", provisions: "[الكلاب؛ القطط]" },
  { id: "2-017", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 141", name: "Chlorophyllin Copper Complex", provisions: "[الكلاب؛ القطط] و [جميع الأنواع ما عدا الكلاب والقطط]" },
  { id: "2-018", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E150b/c/d", name: "Caramel colours", provisions: "[جميع الأنواع]" },
  { id: "2-019", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 151", name: "Brilliant Black PN", provisions: "[الكلاب؛ القطط]" },
  { id: "2-020", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 160b", name: "Bixin", provisions: "[الكلاب؛ القطط]" },
  { id: "2-021", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 171", name: "Titanium dioxide", provisions: "[الكلاب؛ القطط]" },
  { id: "2-022", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "E 172", name: "Iron Oxide Red, Black & Yellow", provisions: "[جميع الأنواع]" },
  { id: "2-023", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "2a104", name: "Quinoline Yellow", provisions: "[الحيوانات غير المنتجة للغذاء]" },
  { id: "2-024", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "2a122", name: "Azorubine or carmoisine", provisions: "[القطط والكلاب]" },
  { id: "2-025", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات أخرى", eNumber: "2a131", name: "Patent blue V", provisions: "[جميع الحيوانات غير المنتجة للغذاء]" },
  { id: "2-026", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – إضافة لون لمنتجات الحيوان", eNumber: "2a161g", name: "Canthaxanthin", provisions: "[الدجاج اللاحم؛ الدواجن الأخرى للتسمين؛ دواجن البيض]" },
  { id: "2-027", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – إضافة لون لمنتجات الحيوان", eNumber: "2a(ii)165", name: "Astaxanthin dimethyldisuccinate", provisions: "[السلمون؛ التروتة]" },
  { id: "2-028", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – إضافة لون لمنتجات الحيوان", eNumber: "2a(ii)167", name: "Red carotenoid-rich Paracoccus carotinifaciens", provisions: "[السلمون؛ التروتة]" },
  { id: "2-029", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "2a(iii)161g", name: "Canthaxanthin", provisions: "[أسماك الزينة؛ طيور الزينة]" },
  { id: "2-030", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 102", name: "Tartrazine", provisions: "[أسماك الزينة؛ طيور الزينة آكلة الحبوب؛ القوارض الصغيرة]" },
  { id: "2-031", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 110", name: "Sunset yellow FCF", provisions: "[أسماك الزينة؛ طيور الزينة آكلة الحبوب؛ القوارض الصغيرة]" },
  { id: "2-032", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 124", name: "Ponceau 4 R", provisions: "[أسماك الزينة]" },
  { id: "2-033", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 127", name: "Erythrosine", provisions: "[أسماك الزينة]" },
  { id: "2-034", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 132", name: "Indigotine", provisions: "[أسماك الزينة]" },
  { id: "2-035", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 141", name: "Chlorophyll copper complex", provisions: "[أسماك الزينة؛ طيور الزينة آكلة الحبوب؛ القوارض الصغيرة]" },
  { id: "2-036", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل – زينة", eNumber: "E 160a", name: "Beta-carotene", provisions: "[الكناري]" },
  { id: "2-037", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 160b", name: "Bixin", provisions: "[أسماك الزينة]" },
  { id: "2-038", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "الكاروتينات والزانثوفيل – زينة", eNumber: "E 161j", name: "Astaxanthin", provisions: "[أسماك الزينة]" },
  { id: "2-039", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "ملونات – أسماك الزينة والطيور", eNumber: "E 172", name: "Iron oxide, red", provisions: "[أسماك الزينة]" },

  // 2b – Flavouring compounds
  { id: "2-040", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة", eNumber: "E 954(iii)", name: "Sodium saccharin", provisions: "[صغار الخنازير]" },
  { id: "2-041", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة", eNumber: "2b16058", name: "Naringin (CAS 10236-47-2 / FLAVIS 16.058)", provisions: "" },
  { id: "2-042", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة", eNumber: "1j514ii", name: "Sodium bisulphate", provisions: "[الحيوانات الأليفة غير المنتجة للغذاء؛ القطط؛ المنك]" },
  { id: "2-043", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة", eNumber: "2b957", name: "Thaumatin (Einecs: 258-822-2)", provisions: "" },
  { id: "2-044", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة", eNumber: "2b959", name: "Neohesperidine dihydrochalcone", provisions: "[صغار الخنازير وخنازير التسمين؛ العجول؛ الخراف؛ الأسماك؛ الكلاب]" },
  { id: "2-045", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة", eNumber: "E 959", name: "Neohesperidine dihydrochalcone", provisions: "[صغار الخنازير؛ الكلاب؛ العجول؛ الأغنام]" },
  { id: "2-046", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة", eNumber: "2b0001", name: "Smoke flavouring extract", provisions: "[الكلاب والقطط]" },

  // 2b – Natural/synthetic chemically defined flavourings (CAS)
  { id: "2-047", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 07.056", name: "3-Methylcyclopentan-1,2-dione", provisions: "" },
  { id: "2-048", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 100-06-1", name: "4-Methoxyacetophenone (FLAVIS 07.038)", provisions: "" },
  { id: "2-049", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 1003-04-9", name: "4,5-Dihydrothiophen-3(2H)-one (FLAVIS 15.012)", provisions: "" },
  { id: "2-050", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 10032-11-8", name: "Hex-3-enyl isovalerate (FLAVIS 09.505)", provisions: "" },
  { id: "2-051", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 10032-13-0", name: "Hexyl isovalerate (FLAVIS 09.529)", provisions: "" },
  { id: "2-052", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 10032-15-2", name: "Hexyl 2-methylbutyrate (FLAVIS 09.507)", provisions: "" },
  { id: "2-053", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 100-51-6", name: "Benzyl alcohol (FLAVIS 02.010)", provisions: "" },
  { id: "2-054", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 100-52-7", name: "Benzaldehyde (FLAVIS 05.013)", provisions: "" },
  { id: "2-055", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 100-53-8", name: "Phenylmethanethiol (FLAVIS 12.005)", provisions: "[القطط والكلاب]" },
  { id: "2-056", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 100-86-7", name: "2-Methyl-1-phenylpropan-2-ol (FLAVIS 02.035)", provisions: "" },
  { id: "2-057", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 101-39-3", name: "alpha-Methylcinnamaldehyde (FLAVIS 05.050)", provisions: "" },
  { id: "2-058", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 101-41-7", name: "Methyl phenylacetate (FLAVIS 09.783)", provisions: "" },
  { id: "2-059", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 101-48-4", name: "1,1-Dimethoxy-2-phenylethane (FLAVIS 06.006)", provisions: "" },
  { id: "2-060", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 101-84-8", name: "Diphenyl ether (FLAVIS 04.035)", provisions: "" },
  { id: "2-061", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 101-86-0", name: "alpha-Hexylcinnamaldehyde (FLAVIS 05.041)", provisions: "" },
  { id: "2-062", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 101-97-3", name: "Ethyl phenylacetate (FLAVIS 09.784)", provisions: "" },
  { id: "2-063", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 102-13-6", name: "Isobutyl phenylacetate (FLAVIS 09.788)", provisions: "" },
  { id: "2-064", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 102-16-9", name: "Benzyl phenylacetate (FLAVIS 09.705)", provisions: "" },
  { id: "2-065", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 102-19-2", name: "3-Methylbutyl phenylacetate (FLAVIS 09.789)", provisions: "" },
  { id: "2-066", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 102-20-5", name: "Phenethyl phenylacetate (FLAVIS 09.707)", provisions: "" },
  { id: "2-067", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-26-4", name: "Methyl cinnamate (FLAVIS 09.740)", provisions: "" },
  { id: "2-068", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-28-6", name: "Benzyl isobutyrate (FLAVIS 09.426)", provisions: "" },
  { id: "2-069", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-36-6", name: "Ethyl cinnamate (FLAVIS 09.730)", provisions: "" },
  { id: "2-070", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-37-7", name: "Benzyl butyrate (FLAVIS 09.051)", provisions: "" },
  { id: "2-071", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-38-8", name: "Benzyl isovalerate (FLAVIS 09.458)", provisions: "" },
  { id: "2-072", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-41-3", name: "Benzyl cinnamate (FLAVIS 09.738)", provisions: "" },
  { id: "2-073", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-45-7", name: "Phenethyl acetate (FLAVIS 09.031)", provisions: "" },
  { id: "2-074", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-48-0", name: "Phenethyl isobutyrate (FLAVIS 09.427)", provisions: "" },
  { id: "2-075", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-52-6", name: "Phenethyl butyrate (FLAVIS 09.168)", provisions: "" },
  { id: "2-076", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-54-8", name: "Cinnamyl acetate (FLAVIS 09.018)", provisions: "" },
  { id: "2-077", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-58-2", name: "3-Phenylpropyl isobutyrate (FLAVIS 09.428)", provisions: "" },
  { id: "2-078", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-59-3", name: "Cinnamyl isobutyrate (FLAVIS 09.470)", provisions: "" },
  { id: "2-079", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مركبات كيميائية محددة", eNumber: "CAS 103-61-7", name: "Cinnamyl butyrate (FLAVIS 09.053)", provisions: "" },

  // 2b – Botanically defined natural products
  { id: "2-080", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مستخلصات نباتية", eNumber: "—", name: "Abies alba Mill. / Abies sibirica Ledeb.: Pine needle oil; Agathosma betulina; Allium cepa (Onion); Allium sativum (Garlic); Althaea officinalis; Amyris balsamifera; Anacardium occidentale; Andrographis paniculata; Anethum graveolens (Dill); Angelica sinensis; Anthemis nobilis (Chamomile); Apium graveolens (Celery seed); Arctium lappa; Armoracia rusticana (Horseradish); Artemisia absinthium (Wormwood); Artemisia annua; Artemisia cina; Artemisia dracunculus (Tarragon); Artemisia pallens (Davana); Artemisia vulgaris (Mugwort); Astragalus membranaceus; Zingiber officinale (Ginger)", provisions: "(للتحقق من الأرقام المرجعية: Council Directive 70/524/EEC)" },

  // 2b – Non-plant natural products
  { id: "2-081", category: 2, categoryLabel: "الإضافات الحسية", functionalGroup: "مواد منكهة – مصدر غير نباتي", eNumber: "—", name: "Sus scrofa (extract from defatted porcine pancreatic glands)", provisions: "[القطط والكلاب والحيوانات آكلة اللحوم والقوارض الأليفة]" },

  // ═══════════════════════════════════════════════
  // CATEGORY 3 – Nutritional Additives
  // ═══════════════════════════════════════════════

  // 3a – Vitamins and provitamins
  { id: "3-001", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a672a/b/c", name: "Retinyl acetate / Retinyl palmitate / Retinyl propionate (Vitamin A)", provisions: "[الدجاج اللاحم وصغار الدواجن؛ الرومي؛ الدواجن الأخرى؛ أبقار الحلاب والتربية؛ العجول؛ الحملان والجداء؛ الماشية والأغنام والماعز للتسمين؛ سائر الأنواع]" },
  { id: "3-002", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a820/3a821", name: "Thiamine hydrochloride / Thiamine mononitrate (Vitamin B1)", provisions: "" },
  { id: "3-003", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "—", name: "Vitamin B2 / Riboflavin; Riboflavin-5'-phosphate ester monosodium salt", provisions: "" },
  { id: "3-004", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a831", name: "Vitamin B6 / Pyridoxine hydrochloride", provisions: "" },
  { id: "3-005", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "—", name: "Vitamin B12 / Cyanocobalamin", provisions: "" },
  { id: "3-006", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a300/3a311/3a312", name: "Ascorbic acid / Sodium ascorbyl phosphate / Sodium calcium ascorbyl phosphate (Vitamin C)", provisions: "" },
  { id: "3-007", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "E 671 / 3a670a", name: "Vitamin D / Vitamin D3; Stabilised form of 25-hydroxycholecalciferol", provisions: "[الأبقار؛ الأغنام؛ العجول؛ الخيول؛ الدجاج اللاحم؛ الرومي؛ الدواجن؛ الأسماك؛ سائر الأنواع]" },
  { id: "3-008", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a841", name: "Calcium-D-pantothenate", provisions: "" },
  { id: "3-009", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a842", name: "D-panthenol", provisions: "" },
  { id: "3-010", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a700", name: "Vitamin E / all-rac-alpha-tocopheryl acetate / RRR-alpha-tocopheryl acetate / RRR alpha tocopherol", provisions: "[جميع الأنواع]" },
  { id: "3-011", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a710/3a711", name: "Menadione sodium bisulphite / Menadione nicotinamide bisulphite (Vitamin K3)", provisions: "" },
  { id: "3-012", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a920/3a921", name: "Betaine anhydrous; Betaine anhydrous from GM sugar beet; Betaine hydrochloride", provisions: "" },
  { id: "3-013", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a925", name: "Betaine anhydrous / Betaine hydrochloride", provisions: "" },
  { id: "3-014", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a880", name: "Biotin", provisions: "" },
  { id: "3-015", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a910", name: "L-carnitine", provisions: "" },
  { id: "3-016", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a911", name: "L-carnitine L-tartrate (LCLT)", provisions: "" },
  { id: "3-017", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a890", name: "Choline chloride", provisions: "" },
  { id: "3-018", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a316", name: "Folic acid", provisions: "" },
  { id: "3-019", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a314", name: "Niacin", provisions: "" },
  { id: "3-020", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a315", name: "Niacinamide", provisions: "" },
  { id: "3-021", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "—", name: "Omega-6 Essential Unsaturated Fatty acids (octadecadienoic acid)", provisions: "[أبقار التربية؛ أبقار الحلاب]" },
  { id: "3-022", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a900", name: "Inositol", provisions: "[الأسماك والقشريات]" },
  { id: "3-023", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "3a370", name: "Taurine", provisions: "[Canidae؛ Felidae؛ Mustelidae؛ الأسماك آكلة اللحوم]" },
  { id: "3-024", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "فيتامينات وبروفيتامينات", eNumber: "E 160a / 3a160(a)", name: "Beta-carotene", provisions: "" },

  // 3b – Trace elements
  { id: "3-025", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "E 1", name: "Iron (Fe): Ferric chloride; Ferric oxide; Ferrous carbonate; Ferrous chelate of amino acids; Ferrous chelate of glycine; Ferrous fumarate; Ferrous sulphate (heptahydrate & monohydrate)", provisions: "" },
  { id: "3-026", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b201", name: "Potassium iodide", provisions: "" },
  { id: "3-027", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b202", name: "Calcium iodate, anhydrous", provisions: "" },
  { id: "3-028", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b203", name: "Coated granulated calcium iodate, anhydrous", provisions: "" },
  { id: "3-029", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b301–3b305", name: "Cobalt compounds: Cobalt(II) acetate; Cobalt(II) carbonate; Cobalt(II) carbonate hydroxide; Cobalt(II) sulphate", provisions: "[المجترات ذات الكرش الوظيفي؛ الخيول؛ القوارض؛ الزواحف العاشبة]" },
  { id: "3-030", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "E 4", name: "Copper (Cu): Basic cupric carbonate; Cupric acetate; Cupric chelate of amino acids; Cupric chloride; Cupric oxide; Cupric sulphate; Cupric chelate of glycine", provisions: "" },
  { id: "3-031", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b409–3b412", name: "Dicopper chloride trihydroxide; Copper chelate of hydroxy analogue of methionine; Copper bilysinate; Copper (I) oxide", provisions: "[جميع الأنواع]" },
  { id: "3-032", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "E 5", name: "Manganese (Mn): Manganese chelate of amino acids; Manganous chloride; Manganous oxide; Manganous sulphate; Manganese chelate of glycine", provisions: "" },
  { id: "3-033", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b510", name: "Manganese chelate of hydroxy analogue of methionine", provisions: "[جميع الأنواع]" },
  { id: "3-034", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "E 6", name: "Zinc (Zn): Zinc acetate; Zinc oxide; Zinc sulphate (heptahydrate & monohydrate); Zinc chelate of amino acids; Zinc chelate of glycine", provisions: "" },
  { id: "3-035", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b601–3b613", name: "Zinc acetate; Zinc chloride; Zinc oxide; Zinc sulphates; Zinc chelate (amino acids/glycine/methionine/protein hydrolysates); Zinc bislysinate", provisions: "[جميع الأنواع]" },
  { id: "3-036", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "E 7", name: "Molybdenum (Mo) – Sodium molybdate", provisions: "" },
  { id: "3-037", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "E 8", name: "Selenium (Se) – Sodium selenite", provisions: "" },
  { id: "3-038", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b810/3b811", name: "Organic Selenium from Saccharomyces cerevisiae (selenised yeast inactivated)", provisions: "[جميع الأنواع]" },
  { id: "3-039", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b812/3b813", name: "Selenomethionine from Saccharomyces cerevisiae", provisions: "" },
  { id: "3-040", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "مركبات العناصر النادرة", eNumber: "3b814–3b817", name: "Hydroxy-analogue of selenomethionine; L-selenomethionine; DL-selenomethionine; Selenomethionine", provisions: "[جميع الأنواع]" },

  // 3c – Amino acids
  { id: "3-041", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "322–325", name: "Lysine: L-lysine (base liquid); L-lysine monohydrochloride; L-lysine monohydrochloride (liquid); L-lysine sulphate", provisions: "" },
  { id: "3-042", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c410", name: "L-threonine (from Escherichia coli fermentation)", provisions: "" },
  { id: "3-043", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "341", name: "Tryptophan / L-tryptophan", provisions: "" },
  { id: "3-044", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c351", name: "L-histidine monohydrochloride monohydrate (from Escherichia coli)", provisions: "[السلمونيات]" },
  { id: "3-045", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c361", name: "L-arginine (from Corynebacterium glutamicum)", provisions: "[جميع الأنواع]" },
  { id: "3-046", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c372", name: "Guanidinoacetic acid", provisions: "[الدجاج اللاحم]" },
  { id: "3-047", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c381", name: "L-isoleucine (from Escherichia coli)", provisions: "" },
  { id: "3-048", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c301–3c309", name: "DL-methionine; Sodium DL-methionine; DL-methionine (protected); L-methionine; DL-methionyl-DL-methionine; Hydroxy analogue of methionine; Calcium salt of HMB; Isopropyl ester of HMB", provisions: "" },
  { id: "3-049", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c370", name: "L-valine (from Escherichia coli or Corynebacterium glutamicum)", provisions: "" },
  { id: "3-050", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c391", name: "L-cystine", provisions: "" },
  { id: "3-051", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "أحماض أمينية وأملاحها", eNumber: "3c401", name: "L-tyrosine", provisions: "" },

  // 3d – Urea
  { id: "3-052", category: 3, categoryLabel: "الإضافات الغذائية", functionalGroup: "اليوريا ومشتقاتها", eNumber: "3d1", name: "Urea", provisions: "[المجترات ذات الكرش الوظيفي]" },

  // ═══════════════════════════════════════════════
  // CATEGORY 4 – Zootechnical Additives
  // ═══════════════════════════════════════════════

  // 4a – Digestibility enhancers
  { id: "4-001", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1", name: "3-phytase", provisions: "[الدجاج اللاحم؛ البياض؛ صغار الخنازير؛ الخنازير للتسمين]" },
  { id: "4-002", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a2", name: "Fermentation product of Aspergillus oryzae", provisions: "[أبقار الحلاب]" },
  { id: "4-003", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a3", name: "Endo-1,4-beta-mannanase", provisions: "[الدجاج اللاحم]" },
  { id: "4-004", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a5/4a6", name: "6-phytase (from Pichia pastoris / Aspergillus oryzae)", provisions: "[الدجاج اللاحم؛ البط للتسمين؛ الرومي للتسمين؛ البياض؛ الدواجن]" },
  { id: "4-005", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a7", name: "Preparation of endo-1,4-beta-xylanase and endo-1,4-beta-glucanase (from Aspergillus niger)", provisions: "[الدجاج اللاحم؛ البياض؛ الرومي؛ البط؛ الدواجن الصغيرة]" },
  { id: "4-006", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a8", name: "Preparation of endo-1,4-beta-xylanase (from Trichoderma reesei)", provisions: "[الدجاج اللاحم؛ البياض؛ الرومي؛ الدواجن الصغيرة]" },
  { id: "4-007", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a9", name: "Preparation of endo-1,4-beta-xylanase and endo-1,3(4)-beta-glucanase (from Trichoderma reesei)", provisions: "[الدجاج اللاحم؛ البياض؛ الرومي]" },
  { id: "4-008", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a10", name: "Preparation of endo-1,4-beta-xylanase, subtilisin and alpha-amylase (from Trichoderma reesei and Bacillus)", provisions: "[الدجاج اللاحم؛ البط؛ الرومي؛ البياض]" },
  { id: "4-009", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a11", name: "Preparation of endo-1,4-beta-xylanase (from Trichoderma reesei)", provisions: "[الدجاج اللاحم؛ البياض؛ البط؛ الرومي؛ الدواجن الصغيرة ما عدا البط]" },
  { id: "4-010", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a12", name: "Preparation of 6-phytase (from Trichoderma reesei)", provisions: "[الدواجن للتسمين والتربية ما عدا الرومي؛ دواجن البيض؛ الرومي]" },
  { id: "4-011", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a13", name: "Serine protease (from Bacillus licheniformis)", provisions: "[الدجاج اللاحم]" },
  { id: "4-012", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a14", name: "Preparation of endo-1,4-beta-xylanase, endo-1,3(4)-beta-glucanase and polygalacturonase (from Trichoderma reesei & Aspergillus aculeatus)", provisions: "[صغار الخنازير]" },
  { id: "4-013", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a15", name: "Preparation of endo-1,4-beta-xylanase and endo-1,3(4)-beta-glucanase (from Trichoderma reesei) – solid and liquid", provisions: "[الرومي؛ البياض؛ الدواجن الأخرى]" },
  { id: "4-014", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a16", name: "Preparation of 6-phytase (from Komagataella pastoris)", provisions: "[الدجاج اللاحم؛ البياض؛ الدواجن الأخرى ما عدا الرومي]" },
  { id: "4-015", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a17", name: "Preparation of alpha galactosidase and endo-1,4-beta-glucanase (from Saccharomyces cerevisiae & Aspergillus niger)", provisions: "[الدجاج اللاحم؛ البياض؛ الدواجن الصغيرة]" },
  { id: "4-016", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a18", name: "6-Phytase (from Aspergillus oryzae)", provisions: "[الدواجن للتسمين]" },
  { id: "4-017", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a19", name: "Preparation of 6-phytase (from Trichoderma reesei)", provisions: "[الدواجن غير البياضة؛ الدواجن البياضة]" },
  { id: "4-018", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a20", name: "Preparation of endo-1,3(4)-beta-glucanase (from Trichoderma reesei)", provisions: "[الدجاج اللاحم]" },
  { id: "4-019", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a21", name: "Preparation of alpha-amylase (from Bacillus licheniformis)", provisions: "[أبقار الحلاب]" },
  { id: "4-020", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a22", name: "Preparation of endo-1,4-beta-xylanase and endo-1,3(4)-beta-glucanase (from Talaromyces versatilis)", provisions: "[الدجاج اللاحم؛ البياض؛ الرومي؛ الدواجن الصغيرة]" },
  { id: "4-021", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a23", name: "Preparation of 6-phytase (from Komagataella pastoris)", provisions: "[الدجاج اللاحم؛ جميع أنواع الدواجن للتسمين والبيض]" },
  { id: "4-022", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a24", name: "6-phytase EC 3.1.3.26 (from Trichoderma reesei ATCC SD-6528)", provisions: "[جميع أنواع الدواجن]" },
  { id: "4-023", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a62", name: "Endo-1,4-beta-xylanase (from Aspergillus niger)", provisions: "[الرومي؛ الدجاج اللاحم؛ البط؛ الدواجن الصغيرة]" },
  { id: "4-024", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1600", name: "3-phytase (Natuphos) from Aspergillus niger", provisions: "[الدجاج اللاحم؛ البياض؛ الرومي؛ البط؛ الدواجن الصغيرة]" },
  { id: "4-025", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1602i", name: "Preparation of endo-1,4-beta-xylanase, endo-1,3(4)-beta-glucanase and endo-1,4-beta-glucanase (from Trichoderma reesei)", provisions: "[الدواجن للتسمين والبيض؛ الرومي]" },
  { id: "4-026", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1604i", name: "Preparation of endo-1,3(4)-beta-glucanase and endo-1,4-beta-xylanase (from Talaromyces versatilis)", provisions: "[جميع أنواع الدواجن]" },
  { id: "4-027", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1606", name: "Endo-1,4-beta-xylanase (from Bacillus subtilis)", provisions: "[البط]" },
  { id: "4-028", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1607", name: "Preparation of endo-1,4-beta-xylanase (from Aspergillus oryzae)", provisions: "[الدواجن للتسمين]" },
  { id: "4-029", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1613", name: "Endo-1,4-beta-xylanase (from Trichoderma longibrachiatum)", provisions: "[البط]" },
  { id: "4-030", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1616", name: "Preparation of endo-1,4-betaglucanase (from Trichoderma citrinoviride)", provisions: "[الدجاج اللاحم والدواجن الصغيرة للتسمين]" },
  { id: "4-031", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1617", name: "Endo-1,4-beta-xylanase (from Trichoderma citrinoviride)", provisions: "[الرومي؛ الدجاج اللاحم؛ البياض؛ الدواجن الصغيرة]" },
  { id: "4-032", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1640", name: "6-Phytase EC 3.1.3.26 (from Schizosaccharomyces pombe)", provisions: "[جميع أنواع الدواجن للتسمين والبيض]" },
  { id: "4-033", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1641(i)", name: "6-Phytase (from Aspergillus oryzae DSM 14223)", provisions: "[الدواجن للتكاثر والبيض؛ السلمونيات]" },
  { id: "4-034", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "محسنات الهضم", eNumber: "4a1642", name: "Endo-1,4-beta-xylanase (from Trichoderma koningii)", provisions: "[الرومي للتسمين والتكاثر]" },

  // 4b – Gut flora stabilisers
  { id: "4-035", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1702", name: "Saccharomyces cerevisiae", provisions: "[ماعز الحلاب؛ أغنام الحلاب؛ الخيول؛ الجاموس الحلوب؛ العجول؛ الأرانب]" },
  { id: "4-036", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4a1704", name: "Saccharomyces cerevisiae", provisions: "[أبقار الحلاب؛ الماشية والمجترات الصغيرة للتسمين]" },
  { id: "4-037", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1705", name: "Enterococcus faecium", provisions: "[الدجاج اللاحم؛ العجول؛ الجداء؛ القطط؛ الدواجن الصغيرة؛ الكلاب]" },
  { id: "4-038", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1706", name: "Enterococcus faecium & Lactobacillus rhamnosus", provisions: "[العجول]" },
  { id: "4-039", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1707", name: "Enterococcus faecium", provisions: "[العجول؛ الدجاج اللاحم؛ الرومي؛ القطط؛ الكلاب]" },
  { id: "4-040", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1708", name: "Enterococcus faecium (solid and water soluble)", provisions: "[العجول]" },
  { id: "4-041", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1710", name: "Saccharomyces cerevisiae", provisions: "[أبقار الحلاب؛ الماشية للتسمين؛ المجترات الصغيرة؛ الخيول]" },
  { id: "4-042", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1711", name: "Saccharomyces cerevisiae", provisions: "[الحملان؛ ماعز الحلاب؛ أغنام الحلاب]" },
  { id: "4-043", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4d1712", name: "Pediococcus acidilactici", provisions: "[البياض (مياه الشرب)؛ الدجاج اللاحم (مياه الشرب)]" },
  { id: "4-044", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1713", name: "Enterococcus faecium", provisions: "[الدجاج اللاحم]" },
  { id: "4-045", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1715", name: "Lactobacillus acidophilus", provisions: "[البياض]" },
  { id: "4-046", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1820", name: "Bacillus subtilis", provisions: "[الدجاج اللاحم؛ البياض؛ الرومي؛ الدواجن الصغيرة؛ الطيور الزخرفية؛ أسماك الزينة]" },
  { id: "4-047", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1821", name: "Bacillus subtilis", provisions: "[الدجاج اللاحم]" },
  { id: "4-048", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1822", name: "Bacillus amyloliquefaciens", provisions: "[الدجاج اللاحم]" },
  { id: "4-049", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1823", name: "Bacillus subtilis", provisions: "[الدجاج اللاحم؛ البياض؛ البط؛ السمان؛ الرومي؛ الحمام؛ الأوز؛ النعام]" },
  { id: "4-050", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1830", name: "Preparation of Clostridium butyricum", provisions: "[الدجاج اللاحم؛ الدواجن الصغيرة؛ الرومي]" },
  { id: "4-051", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1841", name: "Enterococcus faecium", provisions: "[الدجاج اللاحم؛ الدواجن الصغيرة غير البياضة]" },
  { id: "4-052", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "ميكروبات استقرار الأمعاء", eNumber: "4b1890", name: "Bifidobacterium animalis ssp. + Lactobacillus salivarius ssp. + Enterococcus faecium", provisions: "[الدجاج اللاحم؛ الدواجن الصغيرة غير البياضة]" },

  // 4d – Other zootechnical additives
  { id: "4-053", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d1", name: "Lanthanum carbonate octahydrate (Lantharenol)", provisions: "[القطط؛ الكلاب] – تقليل إفراز الفوسفور في البول" },
  { id: "4-054", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d3", name: "Preparation of protected citric acid, sorbic acid, thymol and vanillin", provisions: "[الدجاج اللاحم؛ الدواجن الصغيرة] – تحسين معدل النمو وكفاءة التحويل الغذائي" },
  { id: "4-055", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d4", name: "Dimethylglycine sodium salt", provisions: "[الدجاج اللاحم]" },
  { id: "4-056", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d7", name: "Ammonium chloride", provisions: "[الحملان للتسمين؛ المجترات؛ القطط؛ الكلاب] – تخفيض حموضة البول" },
  { id: "4-057", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d8", name: "Ammonium chloride", provisions: "[المجترات؛ القطط والكلاب] – تخفيض حموضة البول" },
  { id: "4-058", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d10", name: "Preparation of benzoic acid, thymol, eugenol, piperine", provisions: "[الدجاج اللاحم؛ الدواجن الصغيرة] – تحسين كفاءة التحويل الغذائي" },
  { id: "4-059", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d11", name: "Preparation of carvacrol, cinnamaldehyde and capsicum oleoresin", provisions: "[الدجاج اللاحم] – تحسين كفاءة التحويل الغذائي" },
  { id: "4-060", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d12", name: "Bacillus licheniformis", provisions: "[الدجاج اللاحم؛ الدواجن الصغيرة؛ الطيور الزخرفية] – تحسين كفاءة التحويل الغذائي" },
  { id: "4-061", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d161g", name: "Canthaxanthin", provisions: "[دجاج التربية] – تثبيت الأداء التناسلي" },
  { id: "4-062", category: 4, categoryLabel: "الإضافات الحيوية", functionalGroup: "إضافات حيوية أخرى", eNumber: "4d1712", name: "Pediococcus acidilactici", provisions: "[جميع الأسماك؛ السلمونيات؛ الروبيان] – تحسين معدل البقاء والنمو" },
];

export default ANIMAL_FEED_ADDITIVES;
