export interface FeedGuideRow {
  name: string;
  unit: string;
  animals: string;
  min: string;
  max: string;
  notes: string;
}

export interface FeedGuideSection {
  id: string;
  title: string;
  sectionCode: string;
  note?: string;
  rows: FeedGuideRow[];
}

const ANIMAL_FEED_GUIDE: FeedGuideSection[] = [
  {
    id: "minerals",
    sectionCode: "4.1.1",
    title: "المعادن",
    note: "يُحظر كلياً استخدام الزرنيخ في أعلاف الماشية والدواجن",
    rows: [
      {
        name: "Sodium",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0.1",
        max: "0.15",
        notes: "مع مراعاة التوازن بين العناصر الأخرى",
      },
      {
        name: "Chlorine",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "0.15",
        notes: "",
      },
      {
        name: "Calcium",
        unit: "%",
        animals: "صيصان الدواجن",
        min: "0.6",
        max: "1.2",
        notes: "",
      },
      {
        name: "Calcium",
        unit: "%",
        animals: "المواشي",
        min: "3",
        max: "4",
        notes: "",
      },
      {
        name: "Calcium",
        unit: "%",
        animals: "البياض",
        min: "0.4",
        max: "0.7",
        notes: "",
      },
      {
        name: "Total phosphorus",
        unit: "%",
        animals: "الدواجن",
        min: "0.6",
        max: "0.8",
        notes: "",
      },
      {
        name: "Total phosphorus",
        unit: "%",
        animals: "المواشي",
        min: "0.2",
        max: "2.0",
        notes: "",
      },
      {
        name: "Magnesium",
        unit: "%",
        animals: "الدواجن",
        min: "0.05",
        max: "0.06",
        notes: "",
      },
      {
        name: "Magnesium",
        unit: "%",
        animals: "المواشي",
        min: "0.07",
        max: "0.2",
        notes: "",
      },
      {
        name: "Potassium",
        unit: "%",
        animals: "الدواجن",
        min: "0.4",
        max: "0.6",
        notes: "",
      },
      {
        name: "Potassium",
        unit: "%",
        animals: "المواشي",
        min: "—",
        max: "0.8",
        notes: "",
      },
      {
        name: "Copper",
        unit: "%",
        animals: "الدواجن",
        min: "2",
        max: "6",
        notes: "",
      },
      {
        name: "Copper",
        unit: "%",
        animals: "المواشي",
        min: "5",
        max: "10",
        notes: "",
      },
      {
        name: "Iodine",
        unit: "PPM",
        animals: "الدواجن",
        min: "0.3",
        max: "0.35",
        notes: "",
      },
      {
        name: "Iodine",
        unit: "PPM",
        animals: "المواشي",
        min: "0.25",
        max: "0.5",
        notes: "",
      },
      {
        name: "Iron",
        unit: "PPM",
        animals: "الدواجن",
        min: "40",
        max: "80",
        notes: "يُضاف كسلفات وليس كربونات أو أكسيد",
      },
      {
        name: "Iron",
        unit: "PPM",
        animals: "المواشي",
        min: "50",
        max: "100",
        notes: "يُضاف كسلفات وليس كربونات أو أكسيد",
      },
      {
        name: "Magnesium",
        unit: "PPM",
        animals: "الدواجن",
        min: "35",
        max: "60",
        notes: "مع مراعاة التوازن بين العناصر المختلفة",
      },
      {
        name: "Magnesium",
        unit: "PPM",
        animals: "المواشي",
        min: "20",
        max: "40",
        notes: "مع مراعاة التوازن بين العناصر المختلفة",
      },
      {
        name: "Zinc",
        unit: "PPM",
        animals: "الدواجن",
        min: "35",
        max: "70",
        notes: "عند استخدام الحد الأقصى للكالسيوم يُستخدم الحد الأقصى للزنك",
      },
      {
        name: "Zinc",
        unit: "PPM",
        animals: "المواشي",
        min: "—",
        max: "45",
        notes: "عند استخدام الحد الأقصى للكالسيوم يُستخدم الحد الأقصى للزنك",
      },
      {
        name: "Selenium",
        unit: "PPM",
        animals: "الدواجن",
        min: "0.05",
        max: "0.1",
        notes: "لا يُضاف السيلينيوم كعنصر منفرد بل من خلال مادة علفية غنية به كمسحوق السمك",
      },
      {
        name: "Selenium",
        unit: "PPM",
        animals: "أبقار الحلاب",
        min: "0.05",
        max: "0.1",
        notes: "لا يُضاف السيلينيوم كعنصر منفرد بل من خلال مادة علفية غنية به كمسحوق السمك",
      },
      {
        name: "Selenium",
        unit: "PPM",
        animals: "صغار الرومي",
        min: "0.05",
        max: "0.2",
        notes: "لا يُضاف السيلينيوم كعنصر منفرد بل من خلال مادة علفية غنية به كمسحوق السمك",
      },
    ],
  },
  {
    id: "vitamins",
    sectionCode: "4.1.2",
    title: "الفيتامينات",
    rows: [
      {
        name: "Vitamin A",
        unit: "I.U./Kg",
        animals: "جميع أنواع الدواجن",
        min: "10,000",
        max: "20,000",
        notes: "",
      },
      {
        name: "Vitamin D3",
        unit: "I.U./Kg",
        animals: "جميع أنواع الدواجن",
        min: "1,200",
        max: "4,000",
        notes: "",
      },
      {
        name: "Vitamin E",
        unit: "I.U./Kg",
        animals: "جميع أنواع الدواجن",
        min: "25",
        max: "35",
        notes: "",
      },
      {
        name: "Vitamin K",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "1.3",
        max: "4.0",
        notes: "",
      },
      {
        name: "Vitamin B1",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "1.3",
        max: "—",
        notes: "يصل إلى 4.8 في الرومي",
      },
      {
        name: "Vitamin B2",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "4",
        max: "—",
        notes: "يصل إلى 12 في الرومي",
      },
      {
        name: "Nicotinic acid",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "28",
        max: "—",
        notes: "يصل إلى 60 في الرومي",
      },
      {
        name: "Pentothenic acid",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "10",
        max: "—",
        notes: "يصل إلى 19 في الرومي",
      },
      {
        name: "Pyridoxine B6",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "2.5",
        max: "6",
        notes: "",
      },
      {
        name: "Biotin",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "0.1",
        max: "0.2",
        notes: "",
      },
      {
        name: "Folic acid",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "—",
        max: "0.5",
        notes: "يصل إلى 2.4 في الرومي",
      },
      {
        name: "Vitamin B12",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "0.02",
        max: "0.24",
        notes: "",
      },
      {
        name: "Choline",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "600",
        max: "1,800",
        notes: "يصل إلى 2,000 في الرومي",
      },
    ],
  },
  {
    id: "aminoacids",
    sectionCode: "4.1.3",
    title: "الأحماض الأمينية",
    rows: [
      {
        name: "Methionine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.3",
        max: "0.45",
        notes: "قد يصل إلى 0.52",
      },
      {
        name: "Lysine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.5",
        max: "1.7",
        notes: "في الرومي",
      },
      {
        name: "Arginine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.5",
        max: "1.6",
        notes: "",
      },
      {
        name: "Glycine + Serien",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.8",
        max: "1.5",
        notes: "",
      },
      {
        name: "Histadine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.2",
        max: "0.6",
        notes: "",
      },
      {
        name: "Isoleucine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.45",
        max: "1.1",
        notes: "",
      },
      {
        name: "Leucine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.6",
        max: "1.9",
        notes: "",
      },
      {
        name: "Phenylalanin",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.4",
        max: "1",
        notes: "",
      },
      {
        name: "Phenylalanine + tyrosine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.7",
        max: "1.8",
        notes: "",
      },
      {
        name: "Threonine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.35",
        max: "1",
        notes: "",
      },
      {
        name: "Tryptophan",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.12",
        max: "0.26",
        notes: "",
      },
      {
        name: "Valine",
        unit: "%",
        animals: "جميع الدواجن بجميع الأعمار",
        min: "0.53",
        max: "1.2",
        notes: "",
      },
    ],
  },
  {
    id: "flavours",
    sectionCode: "4.2.1",
    title: "معززات النكهات",
    rows: [
      {
        name: "Black honey",
        unit: "%",
        animals: "جميع أنواع الدواجن",
        min: "1",
        max: "3",
        notes: "",
      },
      {
        name: "Nux vomica",
        unit: "PPM",
        animals: "الدواجن البياضة",
        min: "0",
        max: "20",
        notes: "",
      },
    ],
  },
  {
    id: "colour",
    sectionCode: "4.2.2",
    title: "معززات الألوان",
    rows: [
      {
        name: "Carotenoids (xanthophylls)",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Capsanthin",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Beta-apo-8-Carotenal",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Ethylester of beta apo-8-Carotinic acid",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Lutein",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0",
        max: "80",
        notes: "",
      },
      {
        name: "Crystoxantnin",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Violakanthin",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Ciranthin",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Canthaxthin",
        unit: "PPM",
        animals: "الدواجن",
        min: "0",
        max: "80",
        notes: "",
      },
      {
        name: "Zeaxanthin + Cirtran-axanthin",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0",
        max: "150",
        notes: "",
      },
      {
        name: "Carophil red",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0",
        max: "50",
        notes: "",
      },
      {
        name: "Carophil yellow",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0",
        max: "45",
        notes: "",
      },
      {
        name: "Carophil orange",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0",
        max: "80",
        notes: "",
      },
    ],
  },
  {
    id: "binders",
    sectionCode: "4.2.3",
    title: "مواد رابطة ومانعة للتكتل",
    rows: [
      {
        name: "Lignosulphonates",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Silicic acid (Precipitated and dried)",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Silicates free of asbestos",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0",
        max: "2.5",
        notes: "",
      },
      {
        name: "Critic acid",
        unit: "—",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Sodium bentonite",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Wheat flour",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Starch",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Stearates: Sodium",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Stearates: Potasium",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Stearates: Calcium",
        unit: "%",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
    ],
  },
  {
    id: "antioxidants",
    sectionCode: "4.3.1",
    title: "مضادات الأكسدة",
    rows: [
      {
        name: "L-ascorbic acid",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Sodium L-ascrobate",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Calcium L-ascrobate",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "0",
        max: "100",
        notes: "",
      },
      {
        name: "5-6 diacetyl L-ascorbic acid",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "6-palmityl L-ascorbic acid",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Tocopheriol-rich extracts of natural origin",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Synthetic alpha tocopherol",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Synthetic gama tocopherol",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Synthetic delta tocopherol",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Propylgallate",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Butylated hydroxy toluene (BHT)",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Ethoxyguin",
        unit: "PPM",
        animals: "جميع أنواع المواشي والدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
    ],
  },
  {
    id: "antifungs",
    sectionCode: "4.3.2",
    title: "مضادات الفطريات",
    note: "يجوز إضافة خليط من الأملاح المذكورة مع مضادات الأكسدة والمونو-داي جليسيريدات وأملاح الأحماض الدهنية الأمينية المناسبة للاستهلاك البشري",
    rows: [
      {
        name: "Propionic acid (sodium, ammonium & calcium salts)",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "0",
        max: "0.5 – 1",
        notes: "",
      },
      {
        name: "Acetic acid (sodium, ammonium & calcium salts)",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Sorbic acid (sodium, ammonium & calcium salts)",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
      {
        name: "Phosphoric acid (sodium, ammonium & calcium salts)",
        unit: "PPM",
        animals: "جميع أنواع الدواجن",
        min: "—",
        max: "—",
        notes: "",
      },
    ],
  },
  {
    id: "anticoccidial",
    sectionCode: "4.4.1",
    title: "مضادات الكوكسيديا",
    rows: [
      {
        name: "Amprolium",
        unit: "PPM",
        animals: "الدواجن ما عدا البياض",
        min: "62.5",
        max: "125",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Amprolium + ethopabate",
        unit: "PPM",
        animals: "الدواجن والرومي ما عدا البياض",
        min: "66.5",
        max: "133",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Dinitolmide",
        unit: "PPM",
        animals: "الدواجن ما عدا البياض",
        min: "62.5",
        max: "125",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Dimetridazole",
        unit: "PPM",
        animals: "الدواجن ما عدا البياض",
        min: "125",
        max: "150",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Meticlopindol",
        unit: "PPM",
        animals: "الدجاج اللاحم",
        min: "—",
        max: "125",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Meticlopindol",
        unit: "PPM",
        animals: "الأرانب",
        min: "25",
        max: "200",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Decoquinate",
        unit: "PPM",
        animals: "الدجاج اللاحم",
        min: "20",
        max: "40",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Monensin-sodium",
        unit: "PPM",
        animals: "الدجاج اللاحم",
        min: "100",
        max: "125",
        notes: "لا يُستخدم قبل 5 أيام على الأقل من الذبح",
      },
      {
        name: "Robenidine",
        unit: "PPM",
        animals: "الدجاج اللاحم والرومي",
        min: "30",
        max: "36",
        notes: "لا يُستخدم قبل 3 أيام على الأقل من الذبح",
      },
      {
        name: "Nicarbazine",
        unit: "PPM",
        animals: "الدواجن",
        min: "100",
        max: "125",
        notes: "لا يُستخدم أثناء فترة وضع البيض وقبل 7 أيام على الأقل من الذبح",
      },
      {
        name: "Halofuginone",
        unit: "PPM",
        animals: "الدجاج اللاحم",
        min: "2",
        max: "3",
        notes: "لا يُستخدم قبل 5 أيام على الأقل من الذبح",
      },
      {
        name: "Pronidaziole",
        unit: "PPM",
        animals: "الرومي",
        min: "50",
        max: "85",
        notes: "لا يُستخدم قبل 5 أيام على الأقل من الذبح",
      },
    ],
  },
  {
    id: "antibiotics",
    sectionCode: "4.4.2",
    title: "المضادات الحيوية الآمنة",
    rows: [
      {
        name: "Bacitracin zinc",
        unit: "PPM",
        animals: "الرومي والدواجن (26 أسبوعاً)",
        min: "5",
        max: "20",
        notes: "لا يُستخدم مع الدجاج اللاحم",
      },
      {
        name: "Bacitracin zinc",
        unit: "PPM",
        animals: "صغار البياض (ما عدا البط والأوز، 16 أسبوعاً)",
        min: "5",
        max: "20",
        notes: "",
      },
      {
        name: "Bacitracin zinc",
        unit: "PPM",
        animals: "العجول",
        min: "5",
        max: "20",
        notes: "بدائل الحليب فقط",
      },
      {
        name: "Bacitracin zinc",
        unit: "PPM",
        animals: "العجول (6 أشهر)",
        min: "5",
        max: "80",
        notes: "",
      },
      {
        name: "Bacitracin zinc",
        unit: "PPM",
        animals: "الخراف",
        min: "5",
        max: "20",
        notes: "بدائل الحليب فقط",
      },
      {
        name: "Bacitracin zinc",
        unit: "PPM",
        animals: "الخراف (6 أشهر)",
        min: "5",
        max: "80",
        notes: "",
      },
      {
        name: "Virginamycin",
        unit: "PPM",
        animals: "الرومي (26 أسبوعاً)، الدواجن الأخرى وصغار البياض (ما عدا البط والأوز والحمام والبياض، 16 أسبوعاً)",
        min: "5",
        max: "20",
        notes: "",
      },
      {
        name: "Virginamycin",
        unit: "PPM",
        animals: "العجول",
        min: "5",
        max: "20",
        notes: "بدائل الحليب فقط",
      },
      {
        name: "Virginamycin",
        unit: "PPM",
        animals: "العجول (6 أشهر)",
        min: "5",
        max: "80",
        notes: "",
      },
      {
        name: "Flavomycin",
        unit: "PPM",
        animals: "الرومي (26 أسبوعاً)",
        min: "5",
        max: "20",
        notes: "",
      },
      {
        name: "Flavomycin",
        unit: "PPM",
        animals: "الدواجن الأخرى (16 أسبوعاً) وصغار البياض (ما عدا البط والأوز والحمام والبياض)",
        min: "1",
        max: "20",
        notes: "بدائل الحليب فقط",
      },
      {
        name: "Flavomycin",
        unit: "PPM",
        animals: "العجول (6 أشهر)",
        min: "6 – 8",
        max: "16",
        notes: "بدائل الحليب فقط",
      },
    ],
  },
  {
    id: "prohibited_antibiotics",
    sectionCode: "4.4.2.1",
    title: "المضادات الحيوية المحظورة",
    note: "يُحظر استخدام المضادات الحيوية التالية في أعلاف الحيوانات والطيور: Penicillin, Tetracyclines, Sulphonamides, Trimethoprim, Cephalosporims, Streptomycin, Dihydrostreptomycin, Erythromycin, Sulfaquinoxalive, Oxytetracycline",
    rows: [],
  },
  {
    id: "enzymes",
    sectionCode: "4.5",
    title: "الإنزيمات",
    note: "تُضاف الإنزيمات بكميات ضئيلة جداً لأنها في الغالب فعّالة بتركيزات منخفضة. تُعدّ جميع أنواع الإنزيمات من أصل طبيعي، وليست اصطناعية، وغير ضارة بالصحة.",
    rows: [
      {
        name: "Alpha-amylase",
        unit: "—",
        animals: "جميع الأنواع",
        min: "—",
        max: "—",
        notes: "إنزيم طبيعي آمن",
      },
      {
        name: "Glucanases",
        unit: "—",
        animals: "جميع الأنواع",
        min: "—",
        max: "—",
        notes: "إنزيم طبيعي آمن",
      },
      {
        name: "Proteases",
        unit: "—",
        animals: "جميع الأنواع",
        min: "—",
        max: "—",
        notes: "إنزيم طبيعي آمن",
      },
    ],
  },
];

export default ANIMAL_FEED_GUIDE;
