import { EstablishmentFines, FoodFineV2 } from './food-fines-v2';

export type CosmeticsFine = FoodFineV2;

/* helpers */
function fixed(l: number, m: number, s: number): EstablishmentFines {
  return {
    large:  { a: l, b: l, c: l, d: l },
    medium: { a: m, b: m, c: m, d: m },
    small:  { a: s, b: s, c: s, d: s },
  };
}
function rangeHi(la: number, lb: number, lc: number, ld: number): EstablishmentFines {
  const mf = 0.9, sf = 0.8;
  return {
    large:  { a: la, b: lb, c: lc, d: ld },
    medium: { a: Math.round(la*mf), b: Math.round(lb*mf), c: Math.round(lc*mf), d: Math.round(ld*mf) },
    small:  { a: Math.round(la*sf), b: Math.round(lb*sf), c: Math.round(lc*sf), d: Math.round(ld*sf) },
  };
}
function rangeLo(la: number, lb: number, lc: number, ld: number): EstablishmentFines {
  const mf = 0.9, sf = 0.8;
  return {
    large:  { a: la, b: lb, c: lc, d: ld },
    medium: { a: Math.round(la*mf), b: Math.round(lb*mf), c: Math.round(lc*mf), d: Math.round(ld*mf) },
    small:  { a: Math.round(la*sf), b: Math.round(lb*sf), c: Math.round(lc*sf), d: Math.round(ld*sf) },
  };
}

const rHi5000  = rangeHi(5000, 4500, 4000, 3500);
const rLo5000  = rangeLo(2500, 2250, 2000, 1750);
const rHi3000  = rangeHi(3000, 2700, 2400, 2100);
const rLo3000  = rangeLo(1500, 1350, 1200, 1050);
const rHi1000  = rangeHi(1000,  900,  800,  700);
const rLo1000  = rangeLo( 500,  450,  400,  350);
const rHi2500  = rangeHi(2500, 2250, 2000, 1750);
const rLo2500  = rangeLo(1250, 1125, 1000,  875);
const rHi1500  = rangeHi(1500, 1350, 1200, 1050);
const rLo1500  = rangeLo( 750,  675,  600,  525);

export const COSMETICS_FINES: FoodFineV2[] = [
  /* ═══ القسم الأول: مصنع منتجات التجميل ═══ */

  /* الفصل الأول: مخالفات ترخيص المنشأة */
  { articleCode: "1/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "2/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "3/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "تشغيل المصنع في غير ما رخص له", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "4/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "بدء الإنتاج بالمصنع قبل تعيين مدير فني", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "5/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام عند بدء الإنتاج بالمصنع بأن يكون المدير الفني سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "6/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم إبلاغ الهيئة عن تغيير المدير الفني للمصنع خلال خمسة أيام عمل من تاريخ تغيير المدير الفني", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "7/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم تفرغ المدير الفني للمصنع", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "8/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم إبلاغ الهيئة عن التغييرات في المصنع أو المعلومات التي تم تقديمها للحصول على الترخيص", unit: "لكل حالة عدم التزام – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(2000, 1600, 1200), finesMin: fixed(2000, 1600, 1200) },
  { articleCode: "9/1/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المتعلقة بالترخيص المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثاني: مخالفات تداول المنتج التجميلي */
  { articleCode: "1/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي غير مدرج", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 150,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },
  { articleCode: "2/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي يحتوي على مادة أو أكثر من المواد المحظورة", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(25000, 20000, 15000), finesMin: fixed(25000, 20000, 15000) },
  { articleCode: "3/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي يحتوي على مادة مقيدة أو أكثر مخالفة لشروط تقييدها", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "4/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم وجود ملصق تعريفي على عبوة المنتج التجميلي", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(2000, 1600, 1200), finesMin: fixed(2000, 1600, 1200) },
  { articleCode: "5/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي ببيانات أو معلومات تختلف عن ما هو مدرج", unit: "لكل حالة عدم التزام – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "6/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي لا يحتوي على التحذيرات اللازمة على عبوة المنتج التجميلي", unit: "لكل حالة عدم التزام – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "7/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم حفظ أو تخزين المنتج التجميلي بطريقة مناسبة", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(2000, 1600, 1200), finesMin: fixed(2000, 1600, 1200) },
  { articleCode: "8/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "نقل أو استلم منتجات التجميل بوسيلة نقل غير مناسبة لذلك", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "9/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي صدر له قرار سحب أو أعلنت الهيئة عن إلغائه أو حظره أو استدعائه أو تعليق تداوله", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "10/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي فاسد", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "11/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي منتهي الصلاحية", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "12/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بالشروط والضوابط المتعلقة بالإعلان والدعاية عن منتجات التجميل المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "13/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي يحتوي على ما يخالف أحكام الشريعة الإسلامية والآداب العامة", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "14/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي غير مدرج", unit: "لكل دعاية أو إعلان – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },
  { articleCode: "15/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي يحتوي على اسم أو شعار الهيئة بشكل مباشر أو غير مباشر أو اسم أو شعار لجهة رقابية أخرى", unit: "لكل دعاية أو إعلان – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },
  { articleCode: "16/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي قررت الهيئة إلغاء إدراجه أو حظره أو سحبه أو استدعائه أو تعليق تداوله", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "17/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "استعمال معلومات غير صحيحة للترويج للمنتج التجميلي سواء عليه أو في الدعاية له", unit: "لكل حالة عدم التزام – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "18/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم إيقاف الدعاية بعد ثبوت خطرها على الصحة أو بعد طلب الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "19/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي مضبوط أو متعهد عليه بعدم التصرف قبل إنهاء إجراءات فك الحجز (التحريز)", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "20/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بتقديم ما يثبت مصدر شراء المنتج التجميلي", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },
  { articleCode: "21/2/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي مغشوش", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },

  /* الفصل الثالث: مخالفات عامة – مصنع */
  { articleCode: "1/3/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المنتج التجميلي دون وجود ما يثبت إتلافه عن طريق شركة متخصصة في التخلص الآمن من النفايات الطبية", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "2/3/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المنتج التجميلي المضبوط أو المتعهد عليه بعدم التصرف أو صدر له قرار سحب أو استدعاء دون الالتزام بإجراءات الإتلاف المنشورة على موقع الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "3/3/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "4/3/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المصنع أو أحد مرافقه", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "5/3/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "مزاولة المصنع النشاط بعد إغلاقه أو إلغاء ترخيصه من قبل الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "6/3/1", section: 1, sectionLabel: "مصنع منتجات التجميل", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات متعلقة بالمنشأة أو المنتج التجميلي غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },

  /* ═══ القسم الثاني: مستودع (وكيل/موزع) ═══ */

  /* الفصل الأول */
  { articleCode: "1/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "2/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "3/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم إبلاغ الهيئة عن التغييرات في المستودع أو المعلومات المقدمة للحصول على الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "4/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "تشغيل المستودع في غير ما رخص له", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "5/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "بدء نشاط المستودع قبل تعيين مدير فني", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "6/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم تفرغ المدير الفني للمستودع", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "7/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم إبلاغ الهيئة عن تغيير المدير الفني للمستودع", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "8/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بأن يكون المدير الفني للمستودع سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "9/1/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المتعلقة بالترخيص المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثاني: مخالفات تداول المنتج التجميلي – مستودع */
  { articleCode: "1/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي غير مدرج", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 100,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1500, 1200, 900), finesMin: fixed(1500, 1200, 900) },
  { articleCode: "2/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي يحتوي على مادة أو أكثر من المواد المحظورة", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "3/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي يحتوي على مادة مقيدة مخالفة لشروط تقييدها", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "4/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم وجود ملصق تعريفي على عبوة المنتج التجميلي", unit: "لكل شكل وحجم – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "5/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي ببيانات أو معلومات تختلف عن ما هو مدرج", unit: "لكل حالة عدم التزام – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "6/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي لا يحتوي على التحذيرات اللازمة", unit: "لكل حالة عدم التزام – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "7/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم حفظ أو تخزين المنتج التجميلي بطريقة مناسبة", unit: "لكل شكل وحجم – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "8/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "نقل أو استلم منتجات التجميل بوسيلة نقل غير مناسبة", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "9/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي صدر له قرار سحب أو أعلنت الهيئة عن إلغائه أو حظره أو استدعائه", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(12000, 16000, 20000), finesMin: fixed(12000, 16000, 20000) },
  { articleCode: "10/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بالشروط والضوابط المتعلقة بالإعلان والدعاية عن منتجات التجميل", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1500, finesMin: rLo1500 },
  { articleCode: "11/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي يحتوي على ما يخالف أحكام الشريعة الإسلامية والآداب العامة", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "12/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي غير مدرج", unit: "لكل دعاية أو إعلان – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "13/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي يحتوي على اسم أو شعار الهيئة بشكل مباشر أو غير مباشر", unit: "لكل دعاية أو إعلان – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "14/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي قررت الهيئة إلغاء إدراجه أو حظره أو سحبه أو استدعائه أو تعليق تداوله", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "15/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "استعمال معلومات غير صحيحة للترويج للمنتج التجميلي سواء عليه أو في الدعاية له", unit: "لكل حالة عدم التزام – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "16/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي مضبوط أو متعهد عليه بعدم التصرف قبل إنهاء إجراءات فك الحجز (التحريز)", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "17/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بتقديم ما يثبت مصدر شراء المنتج التجميلي", unit: "لكل شكل وحجم – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },
  { articleCode: "18/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام باشتراطات مدونة أسس ممارسة التوزيع والتخزين الجيدة المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "19/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي مغشوش", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "20/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بالأحكام والمسؤوليات بين المؤجر والمستأجر والشروط الخاصة بالتخزين للغير المنشورة على موقع الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "21/2/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المتعلقة بالتداول المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثالث: مخالفات عامة – مستودع */
  { articleCode: "1/3/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المنتج التجميلي دون وجود ما يثبت إتلافه عن طريق شركة متخصصة في التخلص الآمن من النفايات الطبية", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "2/3/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المنتج التجميلي المضبوط أو المتعهد عليه بعدم التصرف أو صدر له قرار سحب أو استدعاء دون الالتزام بإجراءات الإتلاف المنشورة على موقع الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "3/3/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "4/3/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المستودع أو أحد مرافقه", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "5/3/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "مزاولة المستودع النشاط بعد اغلاقه أو الغاء ترخيصه من قبل الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(40000, 32000, 24000), finesMin: fixed(40000, 32000, 24000) },
  { articleCode: "6/3/2", section: 2, sectionLabel: "المستودع (وكيل / موزع)", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات متعلقة بالمنشأة أو المنتج التجميلي غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },

  /* ═══ القسم الثالث: المدرج / المستورد ═══ */

  /* الفصل الأول: مخالفات إدراج المنتج التجميلي */
  { articleCode: "1/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "عدم الالتزام بتقديم ملف معلومات المنتج التجميلي المدرج عند طلبه من الهيئة", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "2/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "ملف معلومات المنتج التجميلي المدرج المقدم للهيئة لا يحتوي على كامل المعلومات المطلوبة للمنتج التجميلي", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi2500, finesMin: rLo2500 },
  { articleCode: "3/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "عدم إبلاغ الهيئة فوراً عن أي تعديل تم على المنتج التجميلي", unit: "لكل حالة عدم التزام – بما لا يزيد على 30,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "4/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "عدم إبلاغ الهيئة فوراً في حال حدوث ضرر سببه المنتج التجميلي أو حدوث خطأ في تصنيعه أو عند استدعائه في أي بلد", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "5/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "عدم إبلاغ الهيئة فوراً عن إساءة استخدام للمنتج التجميلي", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },
  { articleCode: "6/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "عدم حصول المدرج على تفويض من المصنع أو الشركة المنتجة مصدق من جهة موثوقة", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "7/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "إدراج منتج تجميلي في سجل منتجات التجميل بالهيئة يحتوي على مواد محظورة", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(25000, 20000, 15000), finesMin: fixed(25000, 20000, 15000) },
  { articleCode: "8/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "إدراج منتج تجميلي في سجل منتجات التجميل بالهيئة يحتوي على مواد مقيدة مخالفة لشروط تقييدها", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "9/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المتعلقة بالإدراج المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "10/1/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات إدراج المنتج التجميلي", violation: "عدم الالتزام بتقديم ما يثبت مصدر شراء المنتج التجميلي المستورد", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },

  /* الفصل الثاني: مخالفات تداول المنتج التجميلي – مدرج/مستورد */
  { articleCode: "1/2/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي غير مدرج", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 100,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(3000, 2400, 1800), finesMin: fixed(3000, 2400, 1800) },
  { articleCode: "2/2/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي يحتوي على مادة أو أكثر من المواد المحظورة", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(25000, 20000, 15000), finesMin: fixed(25000, 20000, 15000) },
  { articleCode: "3/2/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي فاسد", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "4/2/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي منتهي الصلاحية", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "5/2/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي مغشوش", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "6/2/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المنتج التجميلي", violation: "نقل أو استلم منتجات التجميل بوسيلة نقل غير مناسبة", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "7/3/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "8/3/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "9/3/3", section: 3, sectionLabel: "المدرج / المستورد", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات متعلقة بالمنتج التجميلي غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },

  /* ═══ القسم الرابع: منفذ البيع ═══ */

  /* الفصل الأول: مخالفات تداول المنتج التجميلي */
  { articleCode: "1/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي غير مدرج", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(200, 160, 120), finesMin: fixed(200, 160, 120) },
  { articleCode: "2/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "عدم وجود ملصق تعريفي على عبوة المنتج التجميلي", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(100, 80, 60), finesMin: fixed(100, 80, 60) },
  { articleCode: "3/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي ببيانات أو معلومات تختلف عن ما هو مدرج", unit: "لكل حالة عدم التزام – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(100, 80, 60), finesMin: fixed(100, 80, 60) },
  { articleCode: "4/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي لا يحتوي على التحذيرات اللازمة على عبوة المنتج التجميلي", unit: "لكل شكل وحجم – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(100, 80, 60), finesMin: fixed(100, 80, 60) },
  { articleCode: "5/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "عدم حفظ أو تخزين المنتج التجميلي حسب توصية الشركة الصانعة", unit: "لكل شكل وحجم – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "6/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "نقل أو استلم منتجات التجميل بوسيلة نقل غير مناسبة لذلك", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "7/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي صدر له قرار سحب أو أعلنت الهيئة عن إلغائه أو حظره أو استدعائه أو تعليق تداوله", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "8/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي فاسد", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "9/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي منتهي الصلاحية", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "10/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بالشروط والضوابط المتعلقة بالإعلان والدعاية عن منتجات التجميل المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "11/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي يحتوي على ما يخالف أحكام الشريعة الإسلامية والآداب العامة", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "12/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي غير مدرج", unit: "لكل دعاية أو إعلان – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(200, 160, 120), finesMin: fixed(200, 160, 120) },
  { articleCode: "13/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي يحتوي على اسم أو شعار الهيئة بشكل مباشر أو غير مباشر أو اسم أو شعار لجهة رقابية أخرى", unit: "لكل دعاية أو إعلان – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(200, 160, 120), finesMin: fixed(200, 160, 120) },
  { articleCode: "14/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "الإعلان عن منتج تجميلي قررت الهيئة إلغاء إدراجه أو حظره أو سحبه أو استدعائه أو تعليق تداوله", unit: "لكل دعاية أو إعلان – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(2500, 2000, 1500), finesMin: fixed(2500, 2000, 1500) },
  { articleCode: "15/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "استعمال معلومات غير صحيحة للترويج للمنتج التجميلي سواء عليه أو في الدعاية له", unit: "لكل دعاية أو إعلان – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(200, 160, 120), finesMin: fixed(200, 160, 120) },
  { articleCode: "16/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي مضبوط أو متعهد عليه بعدم التصرف قبل إنهاء إجراءات فك الحجز (التحريز)", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(2500, 2000, 1500), finesMin: fixed(2500, 2000, 1500) },
  { articleCode: "17/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بتقديم ما يثبت مصدر شراء المنتج التجميلي", unit: "لكل شكل وحجم – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "18/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "تداول منتج تجميلي مغشوش", unit: "لكل شكل وحجم للمنتج التجميلي", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "19/1/4", section: 4, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المنتج التجميلي", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المتعلقة بالتداول المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثاني: مخالفات عامة – منفذ البيع */
  { articleCode: "1/2/4", section: 4, sectionLabel: "منفذ البيع", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات عامة", violation: "إتلاف المنتج التجميلي دون وجود ما يثبت إتلافه عن طريق شركة متخصصة في التخلص الآمن من النفايات الطبية", unit: "لكل شكل وحجم للمنتج التجميلي – بما لا يزيد على 10,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "2/2/4", section: 4, sectionLabel: "منفذ البيع", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات عامة", violation: "إتلاف المنتج التجميلي المضبوط أو المتعهد عليه بعدم التصرف أو صدر له قرار سحب أو استدعاء دون الالتزام بإجراءات الإتلاف المنشورة على موقع الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "3/2/4", section: 4, sectionLabel: "منفذ البيع", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "4/2/4", section: 4, sectionLabel: "منفذ البيع", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "5/2/4", section: 4, sectionLabel: "منفذ البيع", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات عامة", violation: "مزاولة المنشأة النشاط بعد إغلاقها أو إلغاء ترخيصها من قبل الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(40000, 32000, 24000), finesMin: fixed(40000, 32000, 24000) },
];
