import { EstablishmentFines, FoodFineV2 } from './food-fines-v2';

export type PharmaFine = FoodFineV2;

function fixed(l: number, m: number, s: number): EstablishmentFines {
  return {
    large:  { a: l, b: l, c: l, d: l },
    medium: { a: m, b: m, c: m, d: m },
    small:  { a: s, b: s, c: s, d: s },
  };
}
function rangeHi(la: number, lb: number, lc: number, ld: number): EstablishmentFines {
  const mf = 0.9, sf = 0.8;
  return {
    large:  { a: la, b: lb, c: lc, d: ld },
    medium: { a: Math.round(la*mf), b: Math.round(lb*mf), c: Math.round(lc*mf), d: Math.round(ld*mf) },
    small:  { a: Math.round(la*sf), b: Math.round(lb*sf), c: Math.round(lc*sf), d: Math.round(ld*sf) },
  };
}
function rangeLo(la: number, lb: number, lc: number, ld: number): EstablishmentFines {
  const mf = 0.9, sf = 0.8;
  return {
    large:  { a: la, b: lb, c: lc, d: ld },
    medium: { a: Math.round(la*mf), b: Math.round(lb*mf), c: Math.round(lc*mf), d: Math.round(ld*mf) },
    small:  { a: Math.round(la*sf), b: Math.round(lb*sf), c: Math.round(lc*sf), d: Math.round(ld*sf) },
  };
}

const rHi5000 = rangeHi(5000, 4500, 4000, 3500);
const rLo5000 = rangeLo(2500, 2250, 2000, 1750);
const rHi3000 = rangeHi(3000, 2700, 2400, 2100);
const rLo3000 = rangeLo(1500, 1350, 1200, 1050);
const rHi2000 = rangeHi(2000, 1800, 1600, 1400);
const rLo2000 = rangeLo(1000,  900,  800,  700);
const rHi1000 = rangeHi(1000,  900,  800,  700);
const rLo1000 = rangeLo( 500,  450,  400,  350);
const rHi4000 = rangeHi(4000, 3600, 3200, 2800);
const rLo4000 = rangeLo(2000, 1800, 1600, 1400);
const rHi500  = rangeHi( 500,  450,  400,  350);
const rLo500  = rangeLo( 250,  225,  200,  175);

export const PHARMA_FINES: FoodFineV2[] = [
  /* ═══ القسم الأول: مصنع المستحضرات الصيدلانية والعشبية ═══ */

  /* الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر */
  { articleCode: "1/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(100000, 80000, 60000), finesMin: fixed(100000, 80000, 60000) },
  { articleCode: "2/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "تشغيل المصنع في غير ما رخص له", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "3/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "4/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بالترخيص أو تسجيل المستحضر الصيدلاني أو العشبي", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "5/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "تغيير مكان أو عنوان المصنع دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(100000, 80000, 60000), finesMin: fixed(100000, 80000, 60000) },
  { articleCode: "6/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "تغيير في اسم المصنع دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "7/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم التقيد بشروط الترخيص المنصوص عليها في النظام واللائحة في حال البيع أو التنازل أو نقل ملكية أو أي تصرف آخر", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "8/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم تعيين مدير فني صيدلي", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "9/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم الالتزام بأن يكون المدير الفني الصيدلي سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "10/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم تفرغ المدير الفني للمصنع", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "11/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم تعيين شخص مؤهل للإفراج عن التشغيلات", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "12/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم تعيين صيدلي مسؤولاً عن مراقبة المواد المخدرة والمؤثرات العقلية في حال تصنيعها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "13/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم الالتزام بأن يكون الصيدلي المسؤول عن مراقبة المواد المخدرة والمؤثرات العقلية سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "14/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "تشغيل المنشأة الصيدلية لصيادلة أو فنيي صيادلة أو غيرهم من الممارسين الصحيين قبل حصولهم على ترخيص مزاولة المهنة من الجهة المختصة", unit: "لكل ممارس", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "15/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "تشغيل المنشأة الصيدلية لصيادلة أو فنيي صيادلة أو غيرهم من الممارسين الصحيين بترخيص مزاولة مهنة منتهٍ", unit: "لكل ممارس", warningApplicable: true, fineType: "range", finesMax: rHi2000, finesMin: rLo1000 },
  { articleCode: "16/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم إشعار الهيئة في حال رغبة مدير المصنع ترك العمل", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "17/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم التزام مسؤول عهدة المواد المخدرة والمؤثرات العقلية عند ترك العمل بتسليم ما في عهدته وفق إجراءات وضوابط المواد المخدرة والمؤثرات العقلية المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "18/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم التزام مقدم طلب التسجيل بالشروط التي منحت بموجبها شهادة التسجيل", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "19/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "لم تقدم المنشأة الصيدلية أو وكيلها طلب تجديد تسجيل المستحضر فور انتهاء صلاحية شهادة تسجيل المستحضر", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: true, fineType: "range", finesMax: rHi4000, finesMin: rLo4000 },
  { articleCode: "20/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم سداد الرسم خلال ثلاثة أشهر من تاريخ الإبلاغ بالموافقة على التسجيل أو التجديد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: true, fineType: "range", finesMax: rHi500, finesMin: rLo500 },
  { articleCode: "21/1/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم إبلاغ الهيئة قبل إجراء أي توسعة بالمصنع أو أعمال إنشائية في خطوط الإنتاج", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(40000, 32000, 24000), finesMin: fixed(40000, 32000, 24000) },

  /* الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي */
  { articleCode: "1/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم التزام المصنع بأسس ممارسة التصنيع الجيد المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "2/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي غير مسجل أو مدرج لدى الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "3/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي مغشوش", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "4/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي محظور أو محذر منه", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "5/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي فاسد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "6/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي منتهي الصلاحية", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "7/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صدر له قرار سحب أو أعلنت الهيئة عن إلغائه أو حظره", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "8/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم حفظ أو تخزين المستحضر الصيدلاني أو العشبي حسب توصية الشركة الصانعة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "9/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "نقل أو استلام المستحضر بوسيلة نقل غير مناسبة لذلك", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "10/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تسويق مستحضر صيدلاني أو عشبي بمعلومات مختلفة عن تلك المعتمدة في نشرة المستحضر", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "11/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم وجود نشرة تعريفية على عبوة المستحضر الصيدلاني أو العشبي", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "12/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم توافق التسمية أو التركيب أو المعلومات المطبوعة على عبوة المستحضر مع تلك المعتمدة لدى الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "13/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "البيع بصورة غير متوازنة لتركيز وشكل وحجم وصيغة دوائية معينة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "14/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم توفر المستحضر الصيدلاني أو العشبي المسجل في الأسواق المحلية", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "45/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "توزيع أو تداول العينات المجانية للأدوية المخدرة أو الخاضعة للرقابة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "46/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تجاوز العينات المجانية المسموح بتوزيعها نسبة 1% من الكمية المصنعة محلياً من المستحضر الصيدلاني أو العشبي", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "47/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "الدعاية والإعلان عن المستحضرات التي يتطلب الحصول عليها وصفة طبية في غير المجلات والمؤتمرات والندوات والنشرات العلمية أو غيرها من الوسائل المخصصة للممارسين الصحيين", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "48/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم توافق نصوص البيانات والنشرات والدعايات والإعلانات في المجلات أو المؤتمرات والندوات والنشرات العلمية مع ما يحتويه من مواد وخواص علاجية وفق ما هو محدد في النشرة الخاصة بالمستحضر المعتمدة لدى الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "49/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "استعمال معلومات غير صحيحة للترويج للمستحضر سواءً عليه أو في الدعاية له", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "50/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "الدعاية والإعلان عن المستحضرات التي يتم صرفها بدون وصفة طبية في وسائل الإعلان المختلفة أو التعديل عليه دون الحصول على موافقة الهيئة", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "51/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "إقامة محاضرة علمية موجهة للممارسين الصحيين دون الالتزام بالشروط والضوابط المعتمدة لدى الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "52/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "إقامة حملات توعية بالأمراض والتثقيف الصحي دون الالتزام بالشروط والضوابط المعتمدة لدى الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "53/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم الحصول على موافقة الهيئة قبل إقامة المحاضرات العلمية الموجهة للممارسين الصحيين", unit: "لكل محاضرة", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "54/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم الحصول على موافقة الهيئة قبل نشر أي حملة توعية بالأمراض أو التثقيف الصحي والموجهة للجمهور", unit: "لكل حملة توعوية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "55/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "الدعاية والإعلان عن مستحضر غير مسجل أو مدرج لدى الهيئة", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "56/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بالإعلان والدعاية", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "57/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بالتداول", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "58/2/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم التزام المصنع المحلي بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بتوفر المستحضرات الصيدلانية والعشبية", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },

  /* الفصل الثالث: مخالفات عامة */
  { articleCode: "1/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المستحضر دون وجود ما يثبت إتلافه عن طريق شركة متخصصة في التخلص الآمن من النفايات الطبية", unit: "لكل تركيز وشكل وحجم وصيغة دوائية – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(2000, 1600, 1200), finesMin: fixed(2000, 1600, 1200) },
  { articleCode: "2/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المستحضر المضبوط أو المتعهد عليه بعدم التصرف أو صدر له قرار سحب أو استدعاء دون الالتزام بإجراءات الإتلاف المنشورة على موقع الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "3/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم الالتزام بإجراءات سحب أو استدعاء المستحضر", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "4/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تنفيذ قرار الهيئة بسحب المستحضر", unit: "لكل قرار", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "5/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم إتمام عملية سحب المستحضر خلال الفترة التي حددتها الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "6/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تزويد الهيئة بتقارير دورية مفصلة عن عملية سحب المستحضر خلال المدة المحددة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "7/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تصفية المصنع بطريقة مخالفة للإجراءات التي حددتها اللائحة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi2000, finesMin: rLo2000 },
  { articleCode: "8/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "9/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "10/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "مزاولة المصنع النشاط بعد إغلاقه أو إلغاء ترخيصه من قبل الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(100000, 80000, 60000), finesMin: fixed(100000, 80000, 60000) },
  { articleCode: "11/3/1", section: 1, sectionLabel: "مصنع المستحضرات الصيدلانية والعشبية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات متعلقة بالمنشأة أو المستحضر الصيدلاني أو العشبي غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },

  /* ═══ القسم الثاني: مستودع وكيل / ممثل الشركة الصانعة للمستحضرات الصيدلانية ═══ */

  /* الفصل الأول */
  { articleCode: "1/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "2/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "3/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "تشغيل المستودع في غير ما رخص له", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "4/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "تغيير مكان أو عنوان المستودع دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "5/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم تعيين مدير فني صيدلي للمستودع", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "6/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم الالتزام بأن يكون مدير المستودع الفني الصيدلي سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "7/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم تفرغ المدير الفني للمستودع", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "8/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم إشعار الهيئة في حال رغبة مدير المستودع ترك العمل", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "9/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم تعيين صيدلي مسؤولاً عن مراقبة المواد المخدرة والمؤثرات العقلية في حال تداولها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "10/1/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بالترخيص أو تسجيل المستحضر", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },

  /* الفصل الثاني: مخالفات تداول المستحضر */
  { articleCode: "1/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي غير مسجل لدى الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "2/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي مغشوش", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "3/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي محظور أو محذر منه", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "4/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي فاسد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "5/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صيدلاني أو عشبي منتهي الصلاحية", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "6/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "تداول مستحضر صدر له قرار سحب دون موافقة الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "7/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم حفظ أو تخزين المستحضر حسب توصية الشركة الصانعة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "8/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "نقل أو استلام المستحضر بوسيلة نقل غير مناسبة", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "9/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عرض أو بيع المستحضر الصيدلاني أو العشبي بسعر أعلى من السعر المحدد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "10/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "البيع بصورة غير متوازنة لتركيز وشكل وحجم وصيغة دوائية معينة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "11/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "بيع المستحضر الصيدلاني أو العشبي إلى جهة غير مرخصة أو شراؤه منها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "12/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "الدعاية والإعلان عن مستحضر يتطلب الحصول عليه وصفة طبية في غير الوسائل المخصصة للممارسين الصحيين", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "13/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "استعمال معلومات غير صحيحة للترويج للمستحضر في الدعاية", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "14/2/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بالتداول", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },

  /* الفصل الثالث: مخالفات عامة */
  { articleCode: "1/3/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "2/3/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "3/3/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "مزاولة المستودع النشاط بعد إغلاقه أو إلغاء ترخيصه من قبل الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "4/3/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات متعلقة بالمنشأة أو المستحضر غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "5/3/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم الالتزام بإجراءات سحب أو استدعاء المستحضر", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "6/3/2", section: 2, sectionLabel: "مستودع وكيل الشركة الصانعة", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تنفيذ قرار الهيئة بسحب المستحضر", unit: "لكل قرار", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },

  /* ═══ القسم الثالث: المكتب العلمي ═══ */
  { articleCode: "1/1/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "2/1/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "3/1/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "تغيير مكان أو عنوان المكتب العلمي دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "4/1/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم تعيين مدير صيدلي للمكتب العلمي", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "5/1/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بأن يكون مدير المكتب العلمي الصيدلي سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "1/2/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "الدعاية والإعلان عن مستحضر يتطلب وصفة طبية في غير الوسائل المخصصة للممارسين الصحيين", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "2/2/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "استعمال معلومات غير صحيحة للترويج للمستحضر في الدعاية", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "3/2/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "الدعاية والإعلان عن مستحضر غير مسجل أو مدرج لدى الهيئة", unit: "لكل دعاية أو إعلان", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "4/2/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "إقامة محاضرة علمية موجهة للممارسين الصحيين دون الالتزام بالشروط والضوابط المعتمدة لدى الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "5/2/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم الحصول على موافقة الهيئة قبل إقامة المحاضرات العلمية الموجهة للممارسين الصحيين", unit: "لكل محاضرة", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "6/2/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر الصيدلاني والعشبي", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بالإعلان والدعاية", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "1/3/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "2/3/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "3/3/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "مزاولة المكتب العلمي النشاط بعد إغلاقه أو إلغاء ترخيصه من قبل الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "4/3/3", section: 3, sectionLabel: "المكتب العلمي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },

  /* ═══ القسم الرابع: مركز الاستشارات الدوائية ═══ */
  { articleCode: "1/1/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "2/1/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "3/1/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم تعيين مدير صيدلي للمركز", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "4/1/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بأن يكون مدير المركز الصيدلي سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "5/1/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بالترخيص", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "1/2/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تقديم الخدمات الاستشارية", violation: "تقديم استشارات دوائية مضللة أو غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "2/2/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تقديم الخدمات الاستشارية", violation: "عدم الاحتفاظ بسجلات الاستشارات الدوائية وفق الشروط المحددة", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "3/2/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تقديم الخدمات الاستشارية", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة المتعلقة بالخدمات الاستشارية", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "1/3/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "2/3/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "3/3/4", section: 4, sectionLabel: "مركز الاستشارات الدوائية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },

  /* ═══ القسم الخامس: مركز تحليل المستحضرات الصيدلانية ═══ */
  { articleCode: "1/1/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "2/1/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "3/1/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم تعيين مدير صيدلي للمركز", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "4/1/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بأن يكون مدير المركز الصيدلي سعودياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "5/1/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة المتعلقة بالترخيص", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "1/2/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تحليل المستحضرات", violation: "إصدار نتائج تحليل غير صحيحة أو مضللة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "2/2/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تحليل المستحضرات", violation: "عدم الالتزام بمعايير أسس ممارسة المختبرات الجيدة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "3/2/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تحليل المستحضرات", violation: "عدم الاحتفاظ بسجلات التحليل وفق الشروط والمدد المحددة", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "4/2/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تحليل المستحضرات", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة المتعلقة بخدمات التحليل", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "1/3/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "2/3/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "3/3/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "مزاولة المركز النشاط بعد إغلاقه أو إلغاء ترخيصه من قبل الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "4/3/5", section: 5, sectionLabel: "مركز تحليل المستحضرات الصيدلانية", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
];
