import { EstablishmentFines, FoodFineV2 } from './food-fines-v2';

export type VeterinaryFine = FoodFineV2;

/* helpers */
function fixed(l: number, m: number, s: number): EstablishmentFines {
  return {
    large:  { a: l, b: l, c: l, d: l },
    medium: { a: m, b: m, c: m, d: m },
    small:  { a: s, b: s, c: s, d: s },
  };
}
function rangeHi(la: number, lb: number, lc: number, ld: number): EstablishmentFines {
  const mf = 0.9, sf = 0.8;
  return {
    large:  { a: la, b: lb, c: lc, d: ld },
    medium: { a: Math.round(la*mf), b: Math.round(lb*mf), c: Math.round(lc*mf), d: Math.round(ld*mf) },
    small:  { a: Math.round(la*sf), b: Math.round(lb*sf), c: Math.round(lc*sf), d: Math.round(ld*sf) },
  };
}
function rangeLo(la: number, lb: number, lc: number, ld: number): EstablishmentFines {
  const mf = 0.9, sf = 0.8;
  return {
    large:  { a: la, b: lb, c: lc, d: ld },
    medium: { a: Math.round(la*mf), b: Math.round(lb*mf), c: Math.round(lc*mf), d: Math.round(ld*mf) },
    small:  { a: Math.round(la*sf), b: Math.round(lb*sf), c: Math.round(lc*sf), d: Math.round(ld*sf) },
  };
}

/* standard range patterns (max fine for large category أ) */
const rHi5000  = rangeHi(5000, 4500, 4000, 3500);
const rLo5000  = rangeLo(2500, 2250, 2000, 1750);
const rHi3000  = rangeHi(3000, 2700, 2400, 2100);
const rLo3000  = rangeLo(1500, 1350, 1200, 1050);
const rHi1000  = rangeHi(1000,  900,  800,  700);
const rLo1000  = rangeLo( 500,  450,  400,  350);
const rHi2000  = rangeHi(2000, 1800, 1600, 1400);
const rLo2000  = rangeLo(1000,  900,  800,  700);
const rHi500   = rangeHi( 500,  450,  400,  350);
const rLo500   = rangeLo( 250,  225,  200,  175);

export const VETERINARY_FINES: FoodFineV2[] = [
  /* ═══ القسم الأول: المصنع المحلي للمستحضرات البيطرية ═══ */

  /* الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري */
  { articleCode: "1/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(100000, 80000, 60000), finesMin: fixed(100000, 80000, 60000) },
  { articleCode: "2/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "3/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "تشغيل المصنع في غير ما رخص له", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "4/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم إسناد الإشراف على المصنع بجميع أقسامه ومختبراته إلى مدير فني", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "5/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "إسناد الإشراف على المصنع بجميع أقسامه ومختبراته إلى مدير فني غير خليجي", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "6/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم تكليف شخص مؤهل ومرخص له للسماح بإطلاق تشغيله كل مستحضر بيطري قبل تداوله", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "7/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم إبلاغ الهيئة بتغيير المسؤول عن الإجازة النهائية لتشغيلات المستحضر البيطري", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "8/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم توفر وسائل الأمان الحيوي والأمن والسلامة بالمصنع", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "9/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم حصول المصنع على موافقة الهيئة قبل بدء الإنتاج لأي خط شكل صيدلاني جديد", unit: "لكل خط شكل صيدلاني جديد", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "10/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "التغيير في المادة الفعالة للمستحضر البيطري المسجل دون موافقة الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "11/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "التغيير في الشكل الصيدلاني أو طريقة الإعطاء دون موافقة الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "12/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم التزام الشركة مانحة الترخيص للتصنيع والشركة المحلية إبلاغ الهيئة خلال مدة لا تقل عن 180 يوماً قبل انتهاء اتفاقية الترخيص بالتصنيع في حال عدم تجديد الاتفاقية", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "13/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بشروط تسجيل المستحضرات متعددة المصادر (الجنيسة) التي تقدم للتسجيل من المصانع المحلية ويتم تصنيعها في بلد خارجي", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "14/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم إبلاغ الهيئة كتابياً عن أي عملية بيع أو شراء أو دمج أو أي إجراء قانوني أو تجاري يتعلق بالشركة أو بأحد مصانعها المسجلة خلال 90 يوماً من إتمام الإجراء", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "15/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم تجديد تسجيل شركات ومصانع المستحضرات البيطرية عند إجراء تغييرات جذرية في مبنى المصنع أو خطوط الإنتاج", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "16/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم تحديد المختص المؤهل المسؤول عن رصد ومتابعة الآثار الجانبية للمستحضر البيطري", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "17/1/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بترخيص وتسجيل المستحضر البيطري", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثاني: مخالفات تداول أو تسويق المستحضر البيطري */
  { articleCode: "1/2/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول أو تسويق المستحضر البيطري", violation: "عدم التزام المصنع بأسس ممارسة التصنيع الجيدة المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "2/2/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول أو تسويق المستحضر البيطري", violation: "تداول مستحضر بيطري مسجل تم التعديل أو التغيير على معلوماته دون موافقة الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "3/2/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول أو تسويق المستحضر البيطري", violation: "تصنيع مستحضر بيطري للغير دون موافقة الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "4/2/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول أو تسويق المستحضر البيطري", violation: "عدم التزام المصنع المحلي بتوفير المستحضر البيطري المسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "5/2/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول أو تسويق المستحضر البيطري", violation: "عدم التزام المصنع المحلي بتوفير مخزون يكفي للاستهلاك المحلي من المستحضر البيطري المسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "6/2/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول أو تسويق المستحضر البيطري", violation: "عدم التزام المصنع المحلي بتوفير مستحضر بيطري مسجل لم يسوق أو يتوقف عن تسويقه", unit: "لكل تركيز وشكل وحجم وصيغة دوائية – بما لا يزيد على 50,000 ريال", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },

  /* الفصل الثالث: مخالفات عامة */
  { articleCode: "1/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المستحضر البيطري دون ما يثبت إتلافه عبر شركة متخصصة في التخلص الآمن من النفايات الطبية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "2/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إتلاف المستحضر المضبوط دون الالتزام بإجراءات الإتلاف", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "3/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "مزاولة المصنع النشاط بعد إغلاقه", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(100000, 80000, 60000), finesMin: fixed(100000, 80000, 60000) },
  { articleCode: "4/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تداول مستحضر بيطري صدر له قرار سحب دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "5/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم الالتزام بإجراءات سحب أو استدعاء المستحضر البيطري", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "6/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تنفيذ قرار الهيئة بسحب المستحضر البيطري", unit: "لكل قرار", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "7/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم إتمام عملية سحب المستحضر البيطري خلال الفترة التي حددتها الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "8/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تزويد الهيئة بتقارير دورية مفصلة لعملية سحب المستحضر البيطري خلال المدة المحددة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "9/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم الالتزام بمتطلبات تحليل المستحضر البيطري المنشورة على موقع الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "10/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "تقديم للهيئة بيانات أو معلومات متعلقة بالمستحضر البيطري غير صحيحة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "11/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "الامتناع عن تقديم معلومات تطلبها الهيئة متعلقة بالمستحضر البيطري", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "12/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "13/3/1", section: 1, sectionLabel: "المصنع المحلي", chapter: 3, chapterLabel: "الفصل الثالث: مخالفات عامة", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },

  /* ═══ القسم الثاني: مستودع وكيل / ممثل الشركة الصانعة للمستحضرات البيطرية ═══ */

  /* الفصل الأول */
  { articleCode: "1/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "2/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "3/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم إبلاغ الهيئة عن أي تغيير في اسم المستودع", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "4/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم إبلاغ الهيئة عن أي تغيير في نشاط المنشأة أو عنوانها أو مكانها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "5/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "تغيير مدير المستودع دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "6/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم تعيين صيدلي أو فني صيدلة أو طبيب بيطري مرخص مديراً للمستودع", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "7/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بأن يكون مدير المستودع (الصيدلي أو فني صيدلة أو الطبيب بيطري) خليجياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "8/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم تعيين صيدلي مرخص في حال كان المستودع يتاجر بالمواد المخدرة والمؤثرات العقلية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "9/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بأن يكون الصيدلي المسؤول عن المواد المخدرة والمؤثرات العقلية خليجياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "10/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بإبلاغ الهيئة عن التغيير في المادة الفعالة للمستحضر البيطري المسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "11/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بإبلاغ الهيئة عن التغيير في الشكل الصيدلاني أو طريقة الإعطاء", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "12/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بإبلاغ الهيئة خلال مدة لا تقل عن 180 يوماً قبل انتهاء اتفاقية الترخيص بالتصنيع في حال عدم تجديد الاتفاقية", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "13/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بشروط تسجيل المستحضرات متعددة المصادر (الجنيسة)", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "14/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم إبلاغ الهيئة كتابياً عن أي عملية بيع أو شراء أو دمج أو أي إجراء قانوني أو تجاري خلال 90 يوماً من إتمام الإجراء", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "15/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم تجديد تسجيل شركات ومصانع المستحضرات البيطرية عند إجراء أي تغيير جذري في مبنى المصنع أو خطوط الإنتاج", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "16/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم تحديد المختص المؤهل المسؤول عن رصد ومتابعة الآثار الجانبية للمستحضر البيطري", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "17/1/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة وتسجيل المستحضر البيطري", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة والمتعلقة بترخيص أو تسجيل المستحضر البيطري", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثاني: مخالفات تداول المستحضر البيطري */
  { articleCode: "1/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري مسجل بمعلومات عبوة تختلف عن المعلومات المسجلة لدى الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "2/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "التعديل على معلومات العبوة دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "3/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عرض أو بيع المستحضر البيطري بسعر أعلى من السعر المحدد من قبل الجهة المختصة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "4/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "بيع مستحضر لم يكن مطبوعاً عليه التسعيرة الرسمية ورقم التسجيل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "range", finesMax: rHi2000, finesMin: rLo2000 },
  { articleCode: "5/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري غير مسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(2000, 1600, 1200), finesMin: fixed(2000, 1600, 1200) },
  { articleCode: "6/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري مغشوش", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "7/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري محظور أو محذر منه", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "8/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بالتقييد الصادر عن الهيئة على المستحضر البيطري", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "9/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري فاسد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "10/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري منتهي الصلاحية", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "11/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم حفظ أو تخزين المستحضر البيطري حسب توصية الشركة الصانعة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "12/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "نقل أو استلام المستحضر البيطري بوسيلة غير مناسبة", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "13/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "الإعلان عن مستحضر لا وصفي دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "14/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "الإعلان عن مستحضر يتطلب وصفة طبية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "15/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "استعمال معلومات غير صحيحة للترويج للمستحضر البيطري", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "16/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم إيقاف الدعاية عند ظهور مخاطر على الصحة العامة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "17/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم إيقاف الدعاية عند طلب الجهة المختصة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "18/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم وضع رقم قرار موافقة على الدعاية على الملصق الدعائي للمستحضر", unit: "للمنشأة", warningApplicable: false, fineType: "range", finesMax: rHi2000, finesMin: rLo2000 },
  { articleCode: "19/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بالشروط والضوابط المتعلقة بالإعلان للمستحضر البيطري", unit: "للمنشأة", warningApplicable: false, fineType: "range", finesMax: rHi500, finesMin: rLo500 },
  { articleCode: "20/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "البيع بصورة غير متوازنة لتركيز وشكل وحجم وصيغة دوائية معينة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "21/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "بيع المستحضر البيطري إلى جهة غير مرخصة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "22/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "شراء المستحضر البيطري من جهة غير مرخصة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "23/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بتقديم ما يثبت مصدر الشراء عند الطلب", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "24/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تخزين مستحضر بيطري تالف أو فاسد أو منتهي الصلاحية بمدة تزيد على سنة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "25/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بالاحتفاظ بسجلات الإتلاف", unit: "للمنشأة", warningApplicable: false, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },
  { articleCode: "26/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري صدر له قرار سحب دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "27/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بإجراءات سحب أو استدعاء المستحضر البيطري", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "28/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم تنفيذ قرار الهيئة بسحب المستحضر البيطري", unit: "لكل قرار", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "29/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم إتمام عملية سحب المستحضر البيطري خلال الفترة المحددة من الهيئة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "30/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم تزويد الهيئة بتقارير دورية مفصلة عن عملية السحب", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "31/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بمتطلبات تحليل المستحضر البيطري", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "32/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تقديم بيانات أو معلومات غير صحيحة للهيئة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "33/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "الامتناع عن تقديم معلومات تطلبها الهيئة", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "34/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "35/2/2", section: 2, sectionLabel: "مستودع وكيل المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },

  /* ═══ القسم الثالث: المستورد ═══ */
  { articleCode: "1/1/3", section: 3, sectionLabel: "المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "2/1/3", section: 3, sectionLabel: "المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "3/1/3", section: 3, sectionLabel: "المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم إبلاغ الهيئة عن أي تغيير في بيانات الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "4/1/3", section: 3, sectionLabel: "المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم تعيين صيدلي أو طبيب بيطري مرخص مديراً للمنشأة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "5/1/3", section: 3, sectionLabel: "المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "الالتزام بأن يكون مدير المنشأة خليجياً", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "6/1/3", section: 3, sectionLabel: "المستورد", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة المتعلقة بالترخيص", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثاني: مخالفات تداول المستحضر البيطري */
  { articleCode: "1/2/3", section: 3, sectionLabel: "المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "استيراد مستحضر بيطري غير مسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "2/2/3", section: 3, sectionLabel: "المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "استيراد مستحضر بيطري محظور", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "3/2/3", section: 3, sectionLabel: "المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "استيراد مستحضر بيطري مغشوش", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "4/2/3", section: 3, sectionLabel: "المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "استيراد مستحضر بيطري فاسد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "5/2/3", section: 3, sectionLabel: "المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بمتطلبات استيراد المستحضرات البيطرية", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "6/2/3", section: 3, sectionLabel: "المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "7/2/3", section: 3, sectionLabel: "المستورد", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },

  /* ═══ القسم الرابع: مستودع موزع المستحضر البيطري ═══ */
  { articleCode: "1/1/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط دون الحصول على ترخيص من الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "2/1/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "ممارسة النشاط بعد انتهاء الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi3000, finesMin: rLo3000 },
  { articleCode: "3/1/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم إبلاغ الهيئة عن أي تغيير في بيانات الترخيص", unit: "للمنشأة", warningApplicable: true, fineType: "range", finesMax: rHi5000, finesMin: rLo5000 },
  { articleCode: "4/1/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم تعيين صيدلي أو فني صيدلة أو طبيب بيطري مرخص مديراً للمستودع", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "5/1/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 1, chapterLabel: "الفصل الأول: مخالفات ترخيص المنشأة", violation: "عدم الالتزام بالشروط أو المتطلبات أو التعاميم المنشورة على موقع الهيئة المتعلقة بالترخيص", unit: "لكل حالة عدم التزام", warningApplicable: true, fineType: "range", finesMax: rHi1000, finesMin: rLo1000 },

  /* الفصل الثاني: مخالفات تداول المستحضر البيطري */
  { articleCode: "1/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري غير مسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(2000, 1600, 1200), finesMin: fixed(2000, 1600, 1200) },
  { articleCode: "2/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري مغشوش", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "3/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري فاسد أو منتهي الصلاحية", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "4/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "نقل أو استلام المستحضر البيطري بوسيلة غير مناسبة", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "5/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم حفظ أو تخزين المستحضر البيطري بالطريقة المناسبة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "6/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري صدر له قرار سحب دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "7/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بإجراءات سحب أو استدعاء المستحضر البيطري", unit: "لكل حالة عدم التزام", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "8/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم تنفيذ قرار الهيئة بسحب المستحضر البيطري", unit: "لكل قرار", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "9/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "بيع المستحضر البيطري من جهة غير مرخصة أو شراؤه منها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(1000, 800, 600), finesMin: fixed(1000, 800, 600) },
  { articleCode: "10/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "إعاقة عمل المفتش عن أداء مهامه التفتيشية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "11/2/4", section: 4, sectionLabel: "مستودع موزع المستحضر", chapter: 2, chapterLabel: "الفصل الثاني: مخالفات تداول المستحضر البيطري", violation: "عدم تمكين المفتش من دخول المنشأة أو أحد مرافقها", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },

  /* ═══ القسم الخامس: منفذ البيع ═══ */
  { articleCode: "1/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري مسجل بمعلومات عبوة تختلف عن المسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "2/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "التعديل على معلومات العبوة دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "3/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "عرض أو بيع المستحضر البيطري بسعر أعلى من السعر المحدد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(500, 400, 300), finesMin: fixed(500, 400, 300) },
  { articleCode: "4/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "بيع مستحضر لم يكن مطبوعاً عليه التسعيرة الرسمية ورقم التسجيل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "range", finesMax: rHi2000, finesMin: rLo2000 },
  { articleCode: "5/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري غير مسجل", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(2000, 1600, 1200), finesMin: fixed(2000, 1600, 1200) },
  { articleCode: "6/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري مغشوش", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "7/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري محظور أو محذر منه", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(50000, 40000, 30000), finesMin: fixed(50000, 40000, 30000) },
  { articleCode: "8/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بالتقييد الصادر عن الهيئة على المستحضر البيطري", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "9/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري فاسد", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(20000, 16000, 12000), finesMin: fixed(20000, 16000, 12000) },
  { articleCode: "10/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "تداول مستحضر بيطري منتهي الصلاحية", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "11/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "عدم حفظ أو تخزين المستحضر البيطري حسب توصية الشركة الصانعة", unit: "لكل تركيز وشكل وحجم وصيغة دوائية", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "12/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "نقل أو استلام المستحضر البيطري بوسيلة غير مناسبة", unit: "لكل عملية نقل أو استلام", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "13/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "الإعلان عن مستحضر لا وصفي دون موافقة الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "14/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "الإعلان عن مستحضر يتطلب وصفة طبية", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(30000, 24000, 18000), finesMin: fixed(30000, 24000, 18000) },
  { articleCode: "15/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "استعمال معلومات غير صحيحة للترويج للمستحضر البيطري", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(5000, 4000, 3000), finesMin: fixed(5000, 4000, 3000) },
  { articleCode: "16/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "عدم إيقاف الدعاية عند ظهور مخاطر على الصحة العامة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(15000, 12000, 9000), finesMin: fixed(15000, 12000, 9000) },
  { articleCode: "17/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "عدم إيقاف الدعاية عند طلب الجهة المختصة", unit: "للمنشأة", warningApplicable: false, fineType: "fixed", finesMax: fixed(10000, 8000, 6000), finesMin: fixed(10000, 8000, 6000) },
  { articleCode: "18/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "عدم وضع رقم قرار موافقة على الدعاية على الملصق الدعائي للمستحضر", unit: "للمنشأة", warningApplicable: false, fineType: "range", finesMax: rHi2000, finesMin: rLo2000 },
  { articleCode: "19/1/5", section: 5, sectionLabel: "منفذ البيع", chapter: 1, chapterLabel: "الفصل الأول: مخالفات تداول المستحضر البيطري", violation: "عدم الالتزام بالشروط والضوابط المتعلقة بالإعلان للمستحضر البيطري المنشورة على موقع الهيئة", unit: "للمنشأة", warningApplicable: false, fineType: "range", finesMax: rHi500, finesMin: rLo500 },
];
