uploads = []
outputs = []

[[generated]]
id = "_668LUsgjfxNzbyjItJxP"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "sfda inspector app icon"

[[generated]]
id = "tcXVRvJ9xbeFW2Wa6yl1N"
uri = "file://attached_assets/icon_option_1.png"
type = "image"
title = "arabic letter meem icon"

[[generated]]
id = "axHIdlnxjUZztbRJA03AK"
uri = "file://attached_assets/icon_option_2.png"
type = "image"
title = "magnifying glass food plate icon"

[[generated]]
id = "JYxrrxMzyhN1zGCwrrWOb"
uri = "file://attached_assets/icon_option_3.png"
type = "image"
title = "inspector badge star icon"

[[generated]]
id = "ptUJgwLDDTUEaICUG_leq"
uri = "file://attached_assets/icon_option_4.png"
type = "image"
title = "clipboard hand inspector icon"

[[generated]]
id = "UW-oTqeKpEMOQd3WGkqeV"
uri = "file://artifacts/mobile/assets/images/adaptive-icon.png"
type = "image"
title = "sfda adaptive icon foreground"

[[generated]]
id = "rbCRY1LVZ6FzvbIrVbr8o"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "sfda splash screen icon"
